from collections import (
    OrderedDict,
    abc as container_abcs,
)
from collections.abc import Iterable, Iterator, Mapping
from typing import Any, Generic, Self, TypeVar, overload
from typing_extensions import (
    TypeVar as TypeVarExt,
    deprecated,
)

from torch import Tensor
from torch._jit_internal import _copy_to_script_wrapper

from .module import Module

__all__ = [
    "Container",
    "ModuleDict",
    "ModuleList",
    "ParameterDict",
    "ParameterList",
    "Sequential",
]
T = TypeVar("T", bound=Module)
_V = TypeVar("_V")

@deprecated(
    "`nn.Container` is deprecated. All of it's functionality is now implemented in `nn.Module`. Subclass that instead.",
    category=FutureWarning,
)
class Container(Module):
    def __init__(self, **kwargs: Any) -> None: ...

class Sequential(Module):
    _modules: dict[str, Module]
    @overload
    def __init__(self, *args: Module) -> None: ...
    @overload
    def __init__(self, arg: OrderedDict[str, Module]) -> None: ...
    def __init__(self, *args) -> None: ...
    @_copy_to_script_wrapper
    def __getitem__(self, idx: slice | int) -> Sequential | Module: ...
    def __setitem__(self, idx: int, module: Module) -> None: ...
    def __delitem__(self, idx: slice | int) -> None: ...
    @_copy_to_script_wrapper
    def __len__(self) -> int: ...
    def __add__(self, other) -> Sequential: ...
    def pop(self, key: int | slice) -> Module: ...
    def __iadd__(self, other) -> Self: ...
    def __mul__(self, other: int) -> Sequential: ...
    def __rmul__(self, other: int) -> Sequential: ...
    def __imul__(self, other: int) -> Self: ...
    @_copy_to_script_wrapper
    def __dir__(self) -> list[str]: ...
    @_copy_to_script_wrapper
    def __iter__(self) -> Iterator[Module]: ...
    # No `__call__` override: `Module.__call__` recovers the return type from
    # `forward` structurally, and an override here would erase it back to `Any`.
    def forward(self, input: Tensor) -> Tensor: ...
    def append(self, module: Module) -> Self: ...
    def insert(self, index: int, module: Module) -> Self: ...
    def extend(self, sequential: Iterable[Module]) -> Self: ...

ModuleT = TypeVarExt("ModuleT", bound=Module, default=Module)

class ModuleList(Module, Generic[ModuleT]):
    _modules: dict[str, ModuleT]
    def __init__(self, modules: Iterable[ModuleT] | None = ...) -> None: ...
    @overload
    def __getitem__(self, idx: slice) -> ModuleList[ModuleT]: ...
    @overload
    def __getitem__(self, idx: int) -> ModuleT: ...
    @_copy_to_script_wrapper
    def __getitem__(self, idx: int | slice) -> ModuleT | ModuleList[ModuleT]: ...
    def __setitem__(self, idx: int, module: ModuleT) -> None: ...
    def __delitem__(self, idx: int | slice) -> None: ...
    @_copy_to_script_wrapper
    def __len__(self) -> int: ...
    @_copy_to_script_wrapper
    def __iter__(self) -> Iterator[ModuleT]: ...
    def __iadd__(self, modules: Iterable[ModuleT]) -> Self: ...
    def __add__(self, other: Iterable[ModuleT]) -> ModuleList[ModuleT]: ...
    @_copy_to_script_wrapper
    def __dir__(self) -> list[str]: ...
    def insert(self, index: int, module: ModuleT) -> None: ...
    def append(self, module: ModuleT) -> Self: ...
    def pop(self, key: int | slice) -> ModuleT: ...
    def extend(self, modules: Iterable[ModuleT]) -> Self: ...

class ModuleDict(Module):
    _modules: dict[str, Module]
    def __init__(self, modules: Mapping[str, Module] | None = ...) -> None: ...
    @_copy_to_script_wrapper
    def __getitem__(self, key: str) -> Module: ...
    def __setitem__(self, key: str, module: Module) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    @_copy_to_script_wrapper
    def __len__(self) -> int: ...
    @_copy_to_script_wrapper
    def __iter__(self) -> Iterator[str]: ...
    @_copy_to_script_wrapper
    def __contains__(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def pop(self, key: str) -> Module: ...
    @_copy_to_script_wrapper
    def keys(self) -> container_abcs.KeysView[str]: ...
    @_copy_to_script_wrapper
    def items(self) -> container_abcs.ItemsView[str, Module]: ...
    @_copy_to_script_wrapper
    def values(self) -> container_abcs.ValuesView[Module]: ...
    def update(self, modules: Mapping[str, Module]) -> None: ...

class ParameterList(Module):
    def __init__(self, values: Iterable[Any] | None = ...) -> None: ...
    @overload
    def __getitem__(self, idx: int) -> Any: ...
    @overload
    def __getitem__(self: T, idx: slice) -> T: ...
    def __getitem__(self, idx) -> Self | Any: ...
    def __setitem__(self, idx: int, param: Any) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __iadd__(self, parameters: Iterable[Any]) -> Self: ...
    def __dir__(self) -> list[str]: ...
    def append(self, value: Any) -> Self: ...
    def extend(self, values: Iterable[Any]) -> Self: ...
    def extra_repr(self) -> str: ...
    def __call__(self, *args, **kwargs): ...

class ParameterDict(Module):
    def __init__(self, parameters: Any = ...) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __reversed__(self) -> Iterator[str]: ...
    def copy(self) -> ParameterDict: ...
    def __contains__(self, key: str) -> bool: ...
    def setdefault(self, key: str, default: Any | None = ...) -> Any: ...
    def clear(self) -> None: ...
    def pop(self, key: str) -> Any: ...
    def popitem(self) -> tuple[str, Any]: ...
    def get(self, key: str, default: Any | None = ...) -> Any: ...
    def fromkeys(
        self, keys: Iterable[str], default: Any | None = ...
    ) -> ParameterDict: ...
    def keys(self) -> container_abcs.KeysView[str]: ...
    def items(self) -> Iterable[tuple[str, Any]]: ...
    def values(self) -> Iterable[Any]: ...
    def update(self, parameters: Mapping[str, Any] | ParameterDict) -> None: ...
    def extra_repr(self) -> str: ...
    def __call__(self, input): ...
    def __or__(self, other: ParameterDict) -> ParameterDict: ...
    def __ror__(self, other: ParameterDict) -> ParameterDict: ...
    def __ior__(self, other: ParameterDict) -> Self: ...
