from typing import Any
from torch import Tensor

from .module import Module

__all__ = ["PixelShuffle", "PixelUnshuffle"]

class PixelShuffle(Module):
    __constants__ = ...
    upscale_factor: int
    def __init__(self, upscale_factor: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def extra_repr(self) -> str: ...

class PixelUnshuffle(Module):
    __constants__ = ...
    downscale_factor: int
    def __init__(self, downscale_factor: int) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...
    def extra_repr(self) -> str: ...
