import torch

from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    BatchFeature,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput, SizeDict
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for Donut."""
logger = ...

class DonutFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_thumbnail: bool | None
    do_align_long_axis: bool | None

@auto_docstring
class DonutImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_thumbnail = ...
    do_align_long_axis = ...
    do_pad = ...
    valid_kwargs = DonutFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[DonutFastImageProcessorKwargs]) -> None: ...
    @auto_docstring
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[DonutFastImageProcessorKwargs]
    ) -> BatchFeature: ...
    def align_long_axis(self, image: torch.Tensor, size: SizeDict) -> torch.Tensor: ...
    def pad_image(
        self, image: torch.Tensor, size: SizeDict, random_padding: bool = ...
    ) -> torch.Tensor: ...
    def pad(self, *args, **kwargs):  # -> Tensor:
        ...
    def thumbnail(self, image: torch.Tensor, size: SizeDict) -> torch.Tensor: ...

__all__ = ["DonutImageProcessorFast"]
