from typing import BinaryIO, NamedTuple, Protocol, runtime_checkable

import os

_UNIT_KM = ...
_UNIT_100M = ...
_UNIT_10M = ...
_UNIT_1M = ...
_UNIT_10CM = ...
_UNIT_CM = ...
_UNIT_MM = ...
_UNIT_0_1MM = ...
_UNIT_0_01MM = ...
_UNIT_UM = ...
_UNIT_INCH = ...
_TIFF_TYPE_SIZES = ...
_HEIF_BRANDS = ...
_HEIF_IROT_TO_EXIF = ...
_JPEG_NO_SOF_MARKERS = ...

@runtime_checkable
class ReadSeekBinary(Protocol):
    def read(self, size: int = ...) -> bytes: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...

type PathInput = str | bytes | os.PathLike[str] | os.PathLike[bytes]
type FileInput = PathInput | BinaryIO | ReadSeekBinary

class ImageInfo(NamedTuple):
    width: int = ...
    height: int = ...
    rotation: int = ...
    xdpi: int = ...
    ydpi: int = ...
    colors: int = ...
    channels: int = ...

def get_info(
    filepath: FileInput,
    *,
    size: bool = ...,
    dpi: bool = ...,
    colors: bool = ...,
    exif_rotation: bool = ...,
    channels: bool = ...,
) -> ImageInfo: ...
def get(filepath: FileInput, *, exif_rotation: bool = ...) -> tuple[int, int]: ...
def getDPI(filepath: FileInput) -> tuple[int, int]: ...
