from collections.abc import Generator
from typing import Any

import contextlib

@contextlib.contextmanager
def optimized_execution(should_optimize) -> Generator[None, Any]: ...
@contextlib.contextmanager
def fuser(name) -> Generator[None, Any]: ...

last_executed_optimized_graph = ...

def set_fusion_strategy(strategy: list[tuple[str, int]]) -> list[tuple[str, int]]: ...
