def get_enum(reduction: str) -> int: ...
def legacy_get_string(
    size_average: bool | None, reduce: bool | None, emit_warning: bool = ...
) -> str: ...
def legacy_get_enum(
    size_average: bool | None, reduce: bool | None, emit_warning: bool = ...
) -> int: ...
