from dataclasses import dataclass

from torch.distributed.tensor._op_schema import OpSchema, StrategyType
from torch.distributed.tensor._ops.utils import register_op_strategy
from torch.distributed.tensor.placement_types import Partial

import torch

aten = ...

@dataclass
class MaskBuffer:
    data: torch.Tensor | None = ...
    refcount: int = ...
    def materialize_mask(self, mask) -> None: ...
    def release_mask(self) -> None: ...
    def apply_mask(self, tensor) -> None: ...

@dataclass(frozen=True)
class _MaskPartial(Partial):
    mask_buffer: MaskBuffer = ...
    offset_shape: torch.Size | None = ...
    offset_dim: int = ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@register_op_strategy(aten.embedding.default)
def embedding_strategy(op_schema: OpSchema) -> StrategyType: ...
@register_op_strategy(aten.embedding_dense_backward.default)
def embedding_dense_backward_strategy(op_schema: OpSchema) -> StrategyType: ...
