from collections.abc import Sequence

from torch.distributed.tensor._op_schema import OpSchema, OpStrategy, StrategyType

aten = ...
pointwise_ops = ...
linear_pointwise_ops = ...

def pointwise_strategy(op_schema: OpSchema, linearity: int = ...) -> OpStrategy: ...
def linear_pointwise_strategy(op_schema: OpSchema) -> StrategyType: ...
def common_pointwise_strategy(
    args_schema: Sequence[object],
    followed_strategy: OpStrategy,
    followed_strategy_index: int,
    linearity: int = ...,
    scalar_tensor_idx: int | None = ...,
) -> OpStrategy: ...

for_each_ops = ...
for_each_linearity_ops = ...

def list_pointwise_strategy(
    op_schema: OpSchema, linearity: bool = ...
) -> StrategyType: ...
def list_linear_pointwise_strategy(op_schema: OpSchema) -> StrategyType: ...

fused_ops = ...
_FUSED_OP_SCALAR_IDX = ...
