from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass

from torch._prims_common import DimsType
from torch.distributed.tensor._op_schema import RuntimeSchemaInfo
from torch.distributed.tensor.placement_types import Placement

import torch

aten = ...
type Shape = tuple[int, ...]

@dataclass
class DimSpec:
    def inputs(self) -> Iterable[DimSpec]: ...

type DimMap = tuple[DimSpec, ...]

@dataclass
class Singleton(DimSpec): ...

@dataclass
class InputDim(DimSpec):
    input_dim: int

@dataclass
class Broadcast(DimSpec):
    dim: DimSpec
    dim_size: int
    @classmethod
    def new(cls, dim: DimSpec, dim_size: int) -> DimSpec: ...
    def inputs(self) -> Iterable[DimSpec]: ...

@dataclass
class NewDim(DimSpec):
    size: int
    @classmethod
    def new(cls, size: int) -> DimSpec: ...

@dataclass
class Repeat(DimSpec):
    input_dim: DimSpec
    times: int
    @classmethod
    def new(cls, dim: DimSpec, times: int) -> DimSpec: ...
    def inputs(self) -> Iterable[DimSpec]: ...

@dataclass
class Flatten(DimSpec):
    input_dims: Sequence[DimSpec]
    @classmethod
    def new(cls, dims: Sequence[DimSpec]) -> DimSpec: ...
    def inputs(self) -> Iterable[DimSpec]: ...

@dataclass
class Split(DimSpec):
    input_dim: DimSpec
    group_shape: Shape
    split_id: int
    @classmethod
    def new(cls, dim: DimSpec, group_shape: tuple[int, ...], idx: int) -> DimSpec: ...
    def inputs(self) -> Iterable[DimSpec]: ...

def dim_pad_left(ndim: int, min_dims: int) -> DimMap: ...
def dim_atleast_3d(ndim: int) -> DimMap: ...
def expand(input_shape: Shape, shape: Shape) -> DimMap: ...
def normalize_sizes(sizes: Shape | tuple[Shape]) -> Shape: ...
def dim_flatten(ndim: int, start_dim=..., end_dim=...) -> DimMap: ...
def dim_movedim(ndim: int, input: DimsType, destination: DimsType) -> DimMap: ...
def dim_repeat(ndim: int, sizes: Shape) -> DimMap: ...
def infer_size(total_size: int, sizes: Shape) -> Shape: ...
def view_groups(from_size: Shape, to_size: Shape) -> DimMap: ...
def dim_tile(ndim: int, dims: tuple[int, ...]) -> DimMap: ...
def dim_transpose(ndim: int, dim1: int, dim2: int) -> DimMap: ...
def dim_squeeze(shape: Shape, dim: int | None = ...) -> DimMap: ...
def dim_unsqueeze(ndim: int, dim: int) -> DimMap: ...
def dim_view_as_real(shape: Shape) -> DimMap: ...
def dim_reduction(ndim: int, dim_or_dims: DimsType | None, keepdim: bool) -> DimMap: ...

dim_maps: dict[Callable[..., torch.Tensor], Callable[..., DimMap]] = ...

def propagate_shape_and_sharding(
    input_src_placements: Sequence[Placement],
    global_input_shape: Shape,
    rule: DimMap,
    mesh_sizes: Shape,
    strict_view: bool = ...,
) -> tuple[Sequence[Placement], Sequence[Placement]]: ...
def register_op_strategy_map(
    aten_op_overload: torch._ops.OpOverload,
    local_op_name: Callable[..., torch.Tensor],
    schema_info: RuntimeSchemaInfo | None = ...,
    strict_view: bool = ...,
) -> None: ...
