from typing import Any, overload

import numpy as np

from .base import GenericTensor, Pipeline, build_pipeline_init_args
from ..utils import add_end_docstrings

logger = ...

@add_end_docstrings(
    build_pipeline_init_args(has_tokenizer=True),
    ...,
)
class FillMaskPipeline(Pipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def get_masked_index(self, input_ids: GenericTensor) -> np.ndarray: ...
    def ensure_exactly_one_mask_token(self, model_inputs: GenericTensor):  # -> None:
        ...
    def preprocess(
        self, inputs, return_tensors=..., tokenizer_kwargs=..., **preprocess_parameters
    ) -> dict[str, GenericTensor]: ...
    def postprocess(self, model_outputs, top_k=..., target_ids=...):  # -> list[Any]:
        ...
    def get_target_ids(self, targets):  # -> NDArray[Any]:
        ...
    @overload
    def __call__(self, inputs: str, **kwargs: Any) -> list[dict[str, Any]]: ...
    @overload
    def __call__(
        self, inputs: list[str], **kwargs: Any
    ) -> list[list[dict[str, Any]]]: ...
    def __call__(
        self, inputs: str | list[str], **kwargs: Any
    ) -> list[dict[str, Any]] | list[list[dict[str, Any]]]: ...
