from typing import Any, overload

from PIL import Image

from .base import Pipeline, build_pipeline_init_args
from ..utils import (
    ExplicitEnum,
    add_end_docstrings,
)

logger = ...

def sigmoid(_outputs):  # -> Any:
    ...
def softmax(_outputs):  # -> Any:
    ...

class ClassificationFunction(ExplicitEnum):
    SIGMOID = ...
    SOFTMAX = ...
    NONE = ...

@add_end_docstrings(
    build_pipeline_init_args(has_image_processor=True),
    ...,
)
class ImageClassificationPipeline(Pipeline):
    function_to_apply: ClassificationFunction = ...
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @overload
    def __call__(
        self, inputs: str | Image.Image, **kwargs: Any
    ) -> list[dict[str, Any]]: ...
    @overload
    def __call__(
        self, inputs: list[str] | list[Image.Image], **kwargs: Any
    ) -> list[list[dict[str, Any]]]: ...
    def __call__(
        self,
        inputs: str | list[str] | Image.Image | list[Image.Image],
        **kwargs: Any,
    ) -> list[dict[str, Any]] | list[list[dict[str, Any]]]: ...
    def preprocess(
        self, image, timeout=...
    ):  # -> transformers.feature_extraction_utils.BatchFeature | Any | transformers.image_processing_base.BatchFeature:
        ...
    def postprocess(
        self, model_outputs, function_to_apply=..., top_k=...
    ):  # -> list[dict[str, Any | str]]:
        ...
