from .base import ArgumentHandler, Pipeline, build_pipeline_init_args
from ..utils import add_end_docstrings

class TableQuestionAnsweringArgumentHandler(ArgumentHandler):
    def __call__(
        self, table=..., query=..., **kwargs
    ):  # -> Dataset[Any] | GeneratorType[Any, Any, Any] | list[dict[Any, Any]] | list[Any] | list[dict[str, Any]]:
        ...

@add_end_docstrings(build_pipeline_init_args(has_tokenizer=True))
class TableQuestionAnsweringPipeline(Pipeline):
    default_input_names = ...
    _pipeline_calls_generate = ...
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    _default_generation_config = ...
    def __init__(self, args_parser=..., **kwargs) -> None: ...
    def batch_inference(self, **inputs):  # -> Any:
        ...
    def sequential_inference(self, **inputs): ...
    def __call__(
        self, *args, **kwargs
    ):  # -> Tensor | list[Any] | PipelineIterator | Generator[Any, Any, None] | None:
        ...
    def preprocess(
        self, pipeline_input, padding=..., truncation=...
    ):  # -> BatchEncoding | Any:
        ...
    def postprocess(
        self, model_outputs
    ):  # -> list[dict[str, str | Any]] | dict[str, str | Any]:
        ...
