from typing import Any, overload

from PIL import Image

from .base import ChunkPipeline, build_pipeline_init_args
from ..utils import add_end_docstrings

logger = ...

@add_end_docstrings(build_pipeline_init_args(has_image_processor=True))
class ZeroShotObjectDetectionPipeline(ChunkPipeline):
    _load_processor = ...
    _load_image_processor = ...
    _load_feature_extractor = ...
    _load_tokenizer = ...
    def __init__(self, **kwargs) -> None: ...
    @overload
    def __call__(
        self,
        image: str | Image.Image,
        candidate_labels: str | list[str],
        **kwargs: Any,
    ) -> list[dict[str, Any]]: ...
    @overload
    def __call__(
        self, image: list[dict[str, Any]], **kwargs: Any
    ) -> list[list[dict[str, Any]]]: ...
    def __call__(
        self,
        image: str | Image.Image | list[dict[str, Any]],
        candidate_labels: str | list[str] | None = ...,
        **kwargs: Any,
    ) -> list[dict[str, Any]] | list[list[dict[str, Any]]]: ...
    def preprocess(
        self, inputs, timeout=...
    ):  # -> Generator[dict[str | Any, bool | Tensor | str | Any | Encoding], Any, None]:
        ...
    def postprocess(self, model_outputs, threshold=..., top_k=...):  # -> list[Any]:
        ...
