from abc import ABCMeta, abstractmethod
from collections.abc import Callable, Iterable
from typing import Any

class BaseObject: ...

EMPTY_ALLOWED_TYPE_AND_PROPERTY_LIST = ...

class JsonObject(BaseObject, metaclass=ABCMeta):
    @property
    @abstractmethod
    def attributes(self) -> set[str]: ...
    def validate_json(self) -> None: ...
    def get_object_attribute(self, key: str) -> Any | None: ...
    def get_non_null_attributes(self) -> dict: ...
    def to_dict(self, *args) -> dict: ...
    def __eq__(self, other: object) -> bool: ...

class JsonValidator:
    def __init__(self, message: str) -> None: ...
    def __call__(self, func: Callable) -> Callable[..., None]: ...

class EnumValidator(JsonValidator):
    def __init__(self, attribute: str, enum: Iterable[str]) -> None: ...
