from ...processing_utils import Unpack, VideosKwargs
from ...video_processing_utils import BaseVideoProcessor

"""Video processor class for PerceptionLM."""

class PerceptionLMFastVideoProcessorInitKwargs(VideosKwargs): ...

class PerceptionLMVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    valid_kwargs = PerceptionLMFastVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(
        self, **kwargs: Unpack[PerceptionLMFastVideoProcessorInitKwargs]
    ) -> None: ...

__all__ = ["PerceptionLMVideoProcessor"]
