from typing import Any
import sys

"""
This file is directly from
https://github.com/ActiveState/appdirs/blob/3fe6a83776843a46f20c2e5587afcffe05e03b39/appdirs.py

The license of https://github.com/ActiveState/appdirs copied below:


# This is the MIT license

Copyright (c) 2010 ActiveState Software Inc.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
__version__ = ...
__version_info__ = ...
unicode = str
if sys.platform.startswith("java"):
    os_name = ...
else:
    system = ...

def user_data_dir(
    appname=..., appauthor=..., version=..., roaming=...
) -> str | Any: ...
def site_data_dir(
    appname=..., appauthor=..., version=..., multipath=...
) -> str | Any: ...
def user_config_dir(
    appname=..., appauthor=..., version=..., roaming=...
) -> str | Any: ...
def site_config_dir(
    appname=..., appauthor=..., version=..., multipath=...
) -> str | Any: ...
def user_cache_dir(
    appname=..., appauthor=..., version=..., opinion=...
) -> str | Any: ...
def user_state_dir(
    appname=..., appauthor=..., version=..., roaming=...
) -> str | Any: ...
def user_log_dir(appname=..., appauthor=..., version=..., opinion=...) -> str | Any: ...

class AppDirs:
    def __init__(
        self, appname=..., appauthor=..., version=..., roaming=..., multipath=...
    ) -> None: ...
    @property
    def user_data_dir(self) -> str | Any: ...
    @property
    def site_data_dir(self) -> str | Any: ...
    @property
    def user_config_dir(self) -> str | Any: ...
    @property
    def site_config_dir(self) -> str | Any: ...
    @property
    def user_cache_dir(self) -> str | Any: ...
    @property
    def user_state_dir(self) -> str | Any: ...
    @property
    def user_log_dir(self) -> str | Any: ...

if system == "win32":
    _get_win_folder = ...
if __name__ == "__main__":
    appname = ...
    appauthor = ...
    props = ...
    dirs = ...
    dirs = ...
    dirs = ...
    dirs = ...
