from torch import Tensor

"""Implement various linear algebra algorithms for low rank matrices."""
__all__ = ["pca_lowrank", "svd_lowrank"]

def get_approximate_basis(
    A: Tensor, q: int, niter: int | None = ..., M: Tensor | None = ...
) -> Tensor: ...
def svd_lowrank(
    A: Tensor, q: int | None = ..., niter: int | None = ..., M: Tensor | None = ...
) -> tuple[Tensor, Tensor, Tensor]: ...
def pca_lowrank(
    A: Tensor, q: int | None = ..., center: bool = ..., niter: int = ...
) -> tuple[Tensor, Tensor, Tensor]: ...
