class PythonDispatcher:
    namespace = ...
    name = ...
    runtime_keys = ...
    alias_keys = ...
    supported_keys = ...
    def __init__(self) -> None: ...
    def keys(self) -> list[str]: ...
    def register(self, dispatchKeys) -> None: ...
    def rawRegistrations(self) -> str: ...
    def rawDispatchTable(self) -> str: ...
    def registrations(self) -> str: ...
    def dispatchTable(self) -> str: ...
