from collections.abc import Callable, Iterator
from numpy import ndarray
from types import NotImplementedType
from typing import Self
from collections.abc import Sequence
from typing import Any, TypeVar, overload
from typing_extensions import ParamSpec

import enum

from torch import _C

import torch

_P = ParamSpec("_P")
_TensorLike = TypeVar("_TensorLike", bound=_C.TensorBase)

class Tensor(torch._C.TensorBase):
    _is_param: bool
    def __deepcopy__(self, memo) -> Tensor: ...
    def __reduce_ex__(
        self, proto
    ) -> tuple[Callable[..., Any], tuple[Any, type[Tensor], Any, Any]]: ...
    def storage(self) -> TypedStorage: ...
    def __setstate__(self, state) -> None: ...
    def __repr__(self, *, tensor_contents=...) -> Any: ...
    def backward(
        self, gradient=..., retain_graph=..., create_graph=..., inputs=...
    ) -> None: ...
    def register_hook(self, hook) -> RemovableHandle: ...
    def register_post_accumulate_grad_hook(self, hook) -> RemovableHandle: ...
    def reinforce(self, reward): ...
    def is_shared(self) -> bool: ...
    def share_memory_(self) -> Self: ...
    def module_load(self, other, assign=...) -> Tensor: ...
    def __reversed__(self) -> Self | Tensor: ...
    def norm(
        self, p: float | str | None = ..., dim=..., keepdim=..., dtype=...
    ) -> Tensor: ...
    def solve(self, other) -> tuple[Tensor, Tensor]: ...
    def lstsq(self, other) -> tuple[Tensor, Tensor]: ...
    def eig(self, eigenvectors=...) -> tuple[Tensor, Tensor]: ...
    def symeig(self, eigenvectors=...) -> tuple[Tensor, Tensor]: ...
    def lu(
        self, pivot=..., get_infos=...
    ) -> tuple[Tensor, Tensor, Tensor] | tuple[Tensor, Tensor]: ...
    def stft(
        self,
        n_fft: int,
        hop_length: int | None = ...,
        win_length: int | None = ...,
        window: Tensor | None = ...,
        center: bool = ...,
        pad_mode: str = ...,
        normalized: bool = ...,
        onesided: bool | None = ...,
        return_complex: bool | None = ...,
        align_to_window: bool | None = ...,
    ) -> Tensor: ...
    def istft(
        self,
        n_fft: int,
        hop_length: int | None = ...,
        win_length: int | None = ...,
        window: Tensor | None = ...,
        center: bool = ...,
        normalized: bool = ...,
        onesided: bool | None = ...,
        length: int | None = ...,
        return_complex: bool = ...,
    ) -> Any: ...
    def resize(self, *sizes) -> None: ...
    def resize_as(self, tensor) -> None: ...
    @overload
    def split(self, split_size: int, dim: int = ...) -> tuple[Tensor, ...]: ...
    @overload
    def split(
        self, split_size: Sequence[int], dim: int = ...
    ) -> tuple[Tensor, ...]: ...
    def unique(
        self, sorted=..., return_inverse=..., return_counts=..., dim=...
    ) -> Any: ...
    def unique_consecutive(
        self, return_inverse=..., return_counts=..., dim=...
    ) -> Any: ...
    def __rsub__(self, other: Tensor | bool | complex) -> Tensor: ...
    def __rdiv__(self, other: Tensor | bool | complex) -> Tensor: ...

    __itruediv__ = ...
    __ipow__ = ...
    def __rmod__(self, other: Tensor | bool | complex) -> Tensor: ...
    def __format__(self, format_spec) -> str: ...
    def __rpow__(self, other: Tensor | bool | complex) -> Tensor: ...
    def __floordiv__(self, other: Tensor | float | bool) -> Tensor: ...
    def __rfloordiv__(self, other: Tensor | float | bool) -> Tensor: ...
    def __rlshift__(self, other: Tensor | bool | complex) -> Tensor: ...
    def __rrshift__(self, other: Tensor | bool | complex) -> Tensor: ...
    def __rmatmul__(self, other: Tensor) -> Tensor: ...

    __pos__ = ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Tensor]: ...
    def __hash__(self) -> int: ...
    def __dir__(self) -> list[str]: ...

    __array_priority__ = ...
    def __array__(self, dtype=...) -> ndarray[_AnyShape, dtype[Any]]: ...
    def __array_wrap__(self, array) -> Tensor: ...
    def __contains__(self, element: Any, /) -> bool: ...
    @property
    def __cuda_array_interface__(
        self,
    ) -> dict[str, str | tuple[int, ...] | int | None]: ...
    def storage_type(self) -> None: ...
    def refine_names(self, *names) -> Tensor: ...
    def align_to(self, *names) -> Tensor: ...
    def unflatten(self, dim: int | str, sizes: Sequence[int]) -> Tensor: ...
    def rename_(self, *names, **rename_map) -> Any: ...
    def rename(self, *names, **rename_map) -> Any: ...
    def to_sparse_coo(self) -> Tensor: ...
    def dim_order(
        self, *, ambiguity_check: bool | list[torch.memory_format] = ...
    ) -> tuple[int, ...]: ...
    @classmethod
    def __torch_function__(
        cls, func, types, args=..., kwargs=...
    ) -> NotImplementedType | list[Any] | tuple[Any, ...] | Tensor: ...

    __torch_dispatch__ = ...
    def __dlpack__(
        self,
        *,
        stream: Any | None = ...,
        max_version: tuple[int, int] | None = ...,
        dl_device: tuple[enum.IntEnum, int] | None = ...,
        copy: bool | None = ...,
    ) -> Any: ...
    def __dlpack_device__(self) -> tuple[enum.IntEnum, int]: ...

    __module__ = ...
