def parse_kwargs(desc) -> dict[str | Any, str | Any]: ...
def merge_dicts(*dicts) -> dict[Any, Any]: ...

common_args = ...
reduceops_common_args = ...
multi_dim_common = ...
single_dim_common = ...
factory_common_args = ...
factory_like_common_args = ...
factory_data_common_args = ...
tf32_notes = ...
rocm_fp16_notes = ...
reproducibility_notes: dict[str, str] = ...
sparse_support_notes = ...
