from collections.abc import Callable
from typing import Any

_blocklisted_modules = ...
_marked_safe_globals_set: set[Callable | tuple[Callable, str]] = ...

class _safe_globals:
    def __init__(self, safe_globals: list[Callable | tuple[Callable, str]]) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type, value, tb) -> None: ...

def get_globals_in_pkl(file) -> set[str]: ...

class Unpickler:
    def __init__(self, file, *, encoding: str = ...) -> None: ...
    def load(self) -> Any: ...
    def pop_mark(self) -> list[Any]: ...
    def persistent_load(self, pid): ...

def load(file, *, encoding: str = ...) -> Any: ...
