from ...video_processing_utils import BaseVideoProcessor

"""Fast Image processor class for SAM2."""

class Sam2VideoVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    def post_process_masks(
        self,
        masks,
        original_sizes,
        reshaped_input_sizes,
        mask_threshold=...,
        binarize=...,
        pad_size=...,
    ):  # -> list[Any]:
        ...

__all__ = ["Sam2VideoVideoProcessor"]
