from typing import Any

cache = ...
__all__ = ["compare", "format_flamegraph", "memory", "segments"]

def format_flamegraph(flamegraph_lines, flamegraph_script=...) -> str: ...
def segments(snapshot, format_flamegraph=...): ...
def memory(snapshot, format_flamegraph=...): ...
def compare(before, after, format_flamegraph=...): ...

class Bytes:
    def __init__(self, value) -> None: ...
    def __add__(self, rhs) -> Bytes: ...

def calc_active(seg) -> int: ...

PAGE_SIZE = ...
legend = ...

def segsum(data) -> str: ...
def trace(data) -> str: ...

_memory_viz_template = ...

def trace_plot(data, device=..., plot_segments=...) -> str: ...
def profile_plot(profile, device=...) -> str: ...
def segment_plot(data: Any, device=...) -> str: ...

if __name__ == "__main__":
    thedir = ...
    fn_name = ...
    pickled = ...
    parser = ...
    subparsers = ...
    description = ...
    stats_a = ...
    description = ...
    trace_a = ...
    description = ...
    segments_a = ...
    description = ...
    memory_a = ...
    description = ...
    compare_a = ...
    plots = ...
    args = ...
