from collections.abc import Sequence

class OAuthStateUtils:
    cookie_name: str
    expiration_seconds: int
    default_cookie_name: str = ...
    default_expiration_seconds: int = ...
    def __init__(
        self, *, cookie_name: str = ..., expiration_seconds: int = ...
    ) -> None: ...
    def build_set_cookie_for_new_state(self, state: str) -> str: ...
    def build_set_cookie_for_deletion(self) -> str: ...
    def is_valid_browser(
        self, state: str | None, request_headers: dict[str, str | Sequence[str]]
    ) -> bool: ...
