from collections.abc import Generator
from contextlib import contextmanager
from typing import Any

from torch._C import DispatchKey
from torch._ops import HigherOrderOperator
from torch._subclasses.fake_tensor import FakeTensorMode
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode

import torch

log = ...

class CallTorchBind(HigherOrderOperator):
    def __init__(self) -> None: ...
    def __call__(self, obj, method, *args, **kwargs) -> None: ...
    @staticmethod
    def schema(obj, method) -> torch.FunctionSchema: ...

call_torchbind = ...
_orig_scriptmethod_call = ...

def torchbind_method_redispatch(self, *args, **kwargs) -> None: ...
@contextmanager
def enable_torchbind_tracing() -> Generator[None, Any]: ...
@call_torchbind.py_impl(DispatchKey.CompositeExplicitAutograd)
def call_torchbind_impl(obj, method, *args, **kwargs) -> Any: ...
@call_torchbind.py_impl(ProxyTorchDispatchMode)
def inner(mode, *args, **kwargs) -> None: ...
@call_torchbind.py_impl(FakeTensorMode)
def call_torchbind_fake(mode, *args, **kwargs) -> PyTree: ...
@call_torchbind.py_functionalize_impl
def call_torchbind_func(ctx, *args, **kwargs) -> Any: ...
