from collections.abc import Iterator

import collections
import dataclasses
import enum

from torch._C import FunctionSchema
from torch._C._autograd import _ProfilerResult
from torch._C._profiler import (
    RecordScope,
    _ExtraFields_Allocation,
    _ExtraFields_TorchOp,
    _ProfilerEvent,
    _TensorMetadata,
)

import torch

type KeyAndID = tuple[Key, int]
type TensorAndID = tuple[TensorKey, int]
log = ...

class Category(enum.Enum):
    INPUT = ...
    TEMPORARY = ...
    ACTIVATION = ...
    GRADIENT = ...
    AUTOGRAD_DETAIL = ...
    PARAMETER = ...
    OPTIMIZER_STATE = ...

_CATEGORY_TO_COLORS = ...
_CATEGORY_TO_INDEX = ...

class Action(enum.Enum):
    PREEXISTING = ...
    CREATE = ...
    INCREMENT_VERSION = ...
    DESTROY = ...

_ACTION_TO_INDEX = ...

@dataclasses.dataclass(eq=True, unsafe_hash=False, frozen=True)
class Key:
    device: torch.device

@dataclasses.dataclass
class _Storage:
    ptr: int
    allocation_id: int

    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@dataclasses.dataclass(eq=True, unsafe_hash=True, frozen=True)
class TensorKey(Key):
    id: int
    storage: _Storage

    def __lt__(self, other: TensorKey) -> bool: ...
    @classmethod
    def from_allocation(cls, alloc: _ExtraFields_Allocation) -> TensorKey | None: ...
    @classmethod
    def from_tensor(cls, t: _TensorMetadata | None) -> TensorKey | None: ...

def extract_parameters(node: _ProfilerEvent) -> Iterator[TensorKey]: ...
def extract_gradients(
    node: _ProfilerEvent,
) -> Iterator[tuple[TensorKey | None, TensorKey]]: ...
def get_scopes(event: _ProfilerEvent | None) -> tuple[RecordScope, ...]: ...

class SchemaMatcher:
    @classmethod
    def inputs_are_mutable(cls, t: _ExtraFields_TorchOp) -> tuple[bool | None, ...]: ...
    @classmethod
    def match_schemas(cls, t: _ExtraFields_TorchOp) -> tuple[FunctionSchema, ...]: ...
    @staticmethod
    def lookup_schemas(name: str) -> tuple[FunctionSchema, ...] | None: ...

class OpTree:
    def __init__(self, result: _ProfilerResult) -> None: ...
    def dfs(self, *args, **kwargs) -> Iterator[_ProfilerEvent]: ...
    @property
    def sorted_nodes(self) -> tuple[_ProfilerEvent, ...]: ...

class SizeMap:
    def __init__(self, op_tree: OpTree) -> None: ...
    def __getitem__(self, key: TensorKey) -> int: ...

@dataclasses.dataclass()
class DataFlowEdge:
    input_version: int | None = ...
    mutated: bool | None = ...
    @property
    def is_allocation(self) -> bool: ...
    @property
    def is_deletion(self) -> bool: ...

class DataFlowNode:
    def __init__(self, event: _ProfilerEvent, graph: DataFlowGraph) -> None: ...
    @property
    def inputs(self) -> dict[TensorKey, tuple[bool, int]]: ...
    @property
    def outputs(self) -> dict[TensorKey, int]: ...
    @property
    def intermediates(self) -> tuple[TensorKey, ...]: ...
    @property
    def start_time(self) -> int: ...

class DataFlowGraph:
    def __init__(self, op_tree: OpTree) -> None: ...
    @property
    def flow_nodes(self) -> tuple[DataFlowNode, ...]: ...
    def validate(self) -> None: ...
    @property
    def leaf_events(self) -> tuple[_ProfilerEvent, ...]: ...
    def lookup(self, key: TensorKey) -> int: ...
    def bump(self, key: TensorKey) -> None: ...
    def delete(self, key: TensorKey) -> None: ...

@dataclasses.dataclass
class CategoryElement:
    by_id: Category | None = ...
    by_key: dict[TensorKey, Category] = ...
    by_version: dict[TensorAndID, Category] = ...
    _by_id_keyset: set[TensorKey] = ...

@dataclasses.dataclass
class CategoryDict:
    _values: collections.defaultdict[int, CategoryElement] = ...
    def set_by_id(self, key: TensorKey, category: Category) -> None: ...
    def set_by_key(self, key: TensorKey, category: Category) -> None: ...
    def set_by_version(
        self, key: TensorKey, version: int, category: Category
    ) -> None: ...
    def setdefault_by_version(
        self, key: TensorKey, version: int, category: Category
    ) -> None: ...
    def get(self, key: Key, version: int) -> Category | None: ...

class MemoryProfile:
    def __init__(self, result: _ProfilerResult) -> None: ...
    @property
    def timeline(self) -> tuple[tuple[int, Action, KeyAndID, int], ...]: ...

class MemoryProfileTimeline:
    def __init__(self, memory_profile) -> None: ...
    def export_memory_timeline(self, path, device_str) -> None: ...
    def export_memory_timeline_raw(self, path, device_str) -> None: ...
    def export_memory_timeline_html(
        self, path, device_str, figsize=..., title=...
    ) -> None: ...
