from dataclasses import dataclass

from torch.autograd.profiler import profile

traverse_dfs = ...
traverse_bfs = ...

@dataclass
class EventMetrics:
    duration_time_ns: int = ...
    self_time_ns: int = ...
    idle_time_ns: int = ...
    queue_depth: int = ...
    @property
    def fraction_idle_time(self) -> float: ...

@dataclass
class Interval:
    start: int
    end: int
    queue_depth: int = ...

class EventKey:
    def __init__(self, event) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def intervals_overlap(self, intervals: list[Interval]) -> int: ...

class BasicEvaluation:
    def __init__(self, prof: profile) -> None: ...
    def compute_self_time(self) -> None: ...
    def compute_queue_depth(self) -> list[Interval]: ...
    def compute_idle_time(self) -> None: ...
    def rank_events(self, length) -> list[EventKey]: ...
    def get_optimizable_events(
        self, length: int = ..., print_enable: bool = ...
    ) -> list[EventKey]: ...

def index_of_first_match(seq, predicate, start=..., end=...) -> int | None: ...
def argmax(seq, key=..., start=..., end=...) -> None: ...
def source_code_location(event) -> Literal["No source code location found"]: ...
