from collections.abc import Generator
from contextlib import contextmanager
from typing import Any

__all__ = ["is_available", "mark", "range", "range_pop", "range_push"]

def is_available() -> bool | None: ...
def range_push(msg) -> None: ...
def range_pop() -> None: ...
def mark(msg) -> None: ...
@contextmanager
def range(msg, *args, **kwargs) -> Generator[None, Any]: ...
