import pypdfium2.internal as pdfium_i

__all__ = ("PdfAttachment",)

class PdfAttachment(pdfium_i.AutoCastable):
    def __init__(self, raw, pdf) -> None: ...
    def get_name(self) -> str: ...
    def get_data(self) -> Array[c_char]: ...
    def set_data(self, data) -> None: ...
    def has_key(self, key) -> Any: ...
    def get_value_type(self, key) -> Any: ...
    def get_str_value(self, key) -> str: ...
    def set_str_value(self, key, value) -> None: ...
