from typing import Any, Self

from numpy import ndarray
from PIL import Image
from torch import dtype

import pypdfium2.internal as pdfium_i

__all__ = ("PdfBitmap", "PdfPosConv")
logger = ...

class PdfBitmap(pdfium_i.AutoCloseable):
    def __init__(
        self, raw, buffer, width, height, stride, format, rev_byteorder, needs_free
    ) -> None: ...
    @property
    def parent(self) -> None: ...
    @classmethod
    def from_raw(cls, raw, rev_byteorder=..., ex_buffer=...) -> Self: ...
    @classmethod
    def new_native(
        cls, width, height, format, rev_byteorder=..., buffer=..., stride=...
    ) -> Self: ...
    @classmethod
    def new_foreign(
        cls, width, height, format, rev_byteorder=..., force_packed=...
    ) -> Self: ...
    @classmethod
    def new_foreign_simple(
        cls, width, height, use_alpha, rev_byteorder=...
    ) -> Self: ...
    def fill_rect(self, color, left, top, width, height) -> None: ...
    def to_numpy(self) -> ndarray[_AnyShape, dtype[Any]]: ...
    def to_pil(self) -> Image.Image: ...
    @classmethod
    def from_pil(cls, pil_image) -> Self: ...
    def get_posconv(self, page) -> PdfPosConv: ...

class PdfPosConv:
    def __init__(self, page, pos_args) -> None: ...
    def to_page(self, bitmap_x, bitmap_y) -> tuple[float, float]: ...
    def to_bitmap(self, page_x, page_y) -> tuple[int, int]: ...
