from collections.abc import Generator, Iterator
from pathlib import Path
from typing import Any, Self

from pypdfium2._helpers.page import PdfPage

import pypdfium2.internal as pdfium_i

__all__ = ("PdfBookmark", "PdfDest", "PdfDocument", "PdfFormEnv", "PdfXObject")
logger = ...

class PdfDocument(pdfium_i.AutoCloseable):
    def __init__(
        self,
        input: str | Path | bytes,
        password: str | None = ...,
        autoclose: bool = ...,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *_) -> None: ...
    @property
    def parent(self) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[PdfPage]: ...
    def __getitem__(self, i: int) -> PdfPage: ...
    def __delitem__(self, i) -> None: ...
    @classmethod
    def new(cls) -> Self: ...
    def init_forms(self, config=...) -> None: ...
    def get_formtype(self) -> Any: ...
    def get_pagemode(self) -> Any: ...
    def is_tagged(self) -> Any: ...
    def save(
        self, dest: str | Path, version: int | None = ..., flags: int = ...
    ) -> None: ...
    def get_identifier(self, type=...) -> list[Any]: ...
    def get_version(self) -> int | None: ...
    def get_metadata_value(self, key) -> str: ...

    METADATA_KEYS = ...
    def get_metadata_dict(self, skip_empty=...) -> dict[str, str]: ...
    def count_attachments(self) -> Any: ...
    def get_attachment(self, index) -> PdfAttachment: ...
    def new_attachment(self, name) -> PdfAttachment: ...
    def del_attachment(self, index) -> None: ...
    def get_page(self, index) -> PdfPage: ...
    def new_page(
        self, width: float, height: float, index: int | None = ...
    ) -> PdfPage: ...
    def del_page(self, index) -> None: ...
    def import_pages(self, pdf, pages=..., index=...) -> None: ...
    def get_page_size(self, index) -> tuple[Any, Any]: ...
    def get_page_label(self, index) -> str: ...
    def page_as_xobject(self, index, dest_pdf) -> PdfXObject: ...
    def get_toc(
        self, max_depth=..., parent=..., level=..., seen=...
    ) -> Generator[PdfBookmark | Any, Any]: ...

_ENC_ERRHANDLER = ...

class PdfFormEnv(pdfium_i.AutoCloseable):
    def __init__(self, raw, pdf, config) -> None: ...
    @property
    def parent(self) -> Any: ...

class PdfXObject(pdfium_i.AutoCloseable):
    def __init__(self, raw, pdf) -> None: ...
    @property
    def parent(self) -> Any: ...
    def as_pageobject(self) -> PdfObject: ...

class PdfBookmark(pdfium_i.AutoCastable):
    def __init__(self, raw, pdf, level) -> None: ...
    def get_title(self) -> str: ...
    def get_count(self) -> Any: ...
    def get_dest(self) -> PdfDest | None: ...

class PdfDest(pdfium_i.AutoCastable):
    def __init__(self, raw, pdf) -> None: ...
    def get_index(self) -> None: ...
    def get_view(self, seqtype=...) -> tuple[Any, list[Any]]: ...
