__all__ = ("PdfMatrix",)

class PdfMatrix:
    def __init__(self, a=..., b=..., c=..., d=..., e=..., f=...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def get(self) -> tuple[int, int, int, int, int, int]: ...
    @classmethod
    def from_raw(cls, raw) -> Self: ...
    def to_raw(self) -> FS_MATRIX: ...
    def multiply(self, other) -> PdfMatrix: ...
    def translate(self, x, y) -> PdfMatrix: ...
    def scale(self, x, y) -> PdfMatrix: ...
    def rotate(self, angle, ccw=..., rad=...) -> PdfMatrix: ...
    def mirror(self, invert_x, invert_y) -> PdfMatrix: ...
    def skew(self, x_angle, y_angle, rad=...) -> PdfMatrix: ...
    def on_point(self, x, y) -> tuple[Any, Any]: ...
    def on_rect(self, left, bottom, right, top) -> tuple[Any, Any, Any, Any]: ...
