from collections.abc import Generator
from typing import Any
import ctypes

from pypdfium2._helpers.bitmap import PdfBitmap

import pypdfium2.internal as pdfium_i

__all__ = ("PdfColorScheme", "PdfPage")
c_float = ctypes.c_float
logger = ...

class PdfPage(pdfium_i.AutoCloseable):
    def __init__(self, raw, pdf, formenv) -> None: ...
    @property
    def parent(self) -> Any: ...
    def get_width(self) -> Any: ...
    def get_height(self) -> Any: ...
    def get_size(self) -> tuple[Any, Any]: ...
    def get_rotation(self) -> int: ...
    def set_rotation(self, rotation) -> None: ...
    def get_mediabox(
        self, fallback_ok=...
    ) -> tuple[float, float, float, float] | None: ...
    def set_mediabox(self, l, b, r, t) -> None: ...
    def get_cropbox(
        self, fallback_ok=...
    ) -> tuple[float, float, float, float] | None: ...
    def set_cropbox(self, l, b, r, t) -> None: ...
    def get_bleedbox(
        self, fallback_ok=...
    ) -> tuple[float, float, float, float] | None: ...
    def set_bleedbox(self, l, b, r, t) -> None: ...
    def get_trimbox(
        self, fallback_ok=...
    ) -> tuple[float, float, float, float] | None: ...
    def set_trimbox(self, l, b, r, t) -> None: ...
    def get_artbox(
        self, fallback_ok=...
    ) -> tuple[float, float, float, float] | None: ...
    def set_artbox(self, l, b, r, t) -> None: ...
    def get_bbox(self) -> tuple[Any, Any, Any, Any]: ...
    def get_textpage(self) -> PdfTextPage: ...
    def insert_obj(self, pageobj) -> None: ...
    def remove_obj(self, pageobj) -> None: ...
    def gen_content(self) -> None: ...
    def get_objects(
        self, filter=..., max_depth=..., form=..., level=..., textpage=...
    ) -> Generator[PdfObject | Any, Any, None]: ...
    def flatten(self, flag=...) -> Any: ...
    def render(
        self,
        scale: float = ...,
        rotation: int = ...,
        crop: tuple[float, float, float, float] = ...,
        may_draw_forms: bool = ...,
        bitmap_maker=...,
        color_scheme=...,
        fill_to_stroke: bool = ...,
        **kwargs: object,
    ) -> PdfBitmap: ...

class PdfColorScheme:
    def __init__(self, path_fill, path_stroke, text_fill, text_stroke) -> None: ...
    def convert(self, rev_byteorder) -> FPDF_COLORSCHEME: ...
