from pypdfium2._lazy import cached_property

import pypdfium2.internal as pdfium_i

__all__ = ("PdfFont", "PdfImage", "PdfObject", "PdfTextObj")
logger = ...

class PdfObject(pdfium_i.AutoCloseable):
    def __new__(cls, raw, *args, **kwargs) -> Self: ...
    def __init__(
        self,
        raw,
        page=...,
        pdf=...,
        container=...,
        level=...,
        textpage=...,
        tracked=...,
    ) -> None: ...
    @property
    def parent(self) -> None: ...
    def get_bounds(self) -> tuple[float, float, float, float]: ...
    def get_quad_points(
        self,
    ) -> tuple[tuple[Any, Any], tuple[Any, Any], tuple[Any, Any], tuple[Any, Any]]: ...
    def get_matrix(self) -> PdfMatrix: ...
    def set_matrix(self, matrix) -> None: ...
    def transform(self, matrix) -> None: ...

class PdfTextObj(PdfObject):
    def __init__(self, *args, textpage=..., **kwargs) -> None: ...
    def extract(self) -> str: ...
    def get_font(self) -> PdfFont: ...
    def get_font_size(self) -> float: ...

class PdfFont(pdfium_i.AutoCloseable):
    def __init__(self, raw, parent=..., needs_free=...) -> None: ...
    @cached_property
    def is_embedded(self) -> Any: ...
    def get_base_name(self, errors=...) -> str: ...
    def get_family_name(self, errors=...) -> str: ...
    def get_weight(self) -> Any: ...

    STANDARD_FONTS = ...
    @classmethod
    def load_standard(cls, pdf, name) -> Self: ...

class PdfImage(PdfObject):
    SIMPLE_FILTERS = ...
    @classmethod
    def new(cls, pdf) -> Self: ...
    def get_metadata(self) -> struct_FPDF_IMAGEOBJ_METADATA: ...
    def get_px_size(self) -> tuple[int, int]: ...
    def load_jpeg(self, source, pages=..., inline=..., autoclose=...) -> None: ...
    def set_bitmap(self, bitmap, pages=...) -> None: ...
    def get_bitmap(self, render=..., scale_to_original=...) -> PdfBitmap: ...
    def get_data(self, decode_simple=...) -> Any: ...
    def get_filters(self, skip_simple=...) -> list[Any]: ...
    def extract(self, dest, *args, **kwargs) -> None: ...

_ImageInfo = ...

class _ImageExtractionError(Exception): ...
