from typing import Any

from pypdfium2._lazy import cached_property

import pypdfium2.internal as pdfium_i

__all__ = ("PdfDefaultTTFMap", "PdfSysfontBase")
logger = ...

class _DefaultSysfontInfoClass(pdfium_i.AutoCastable):
    def __init__(self) -> None: ...
    @cached_property
    def raw(self) -> Any: ...
    def close(self) -> None: ...

_DefaultSysfontInfo = ...

class _DefaultTTFMapClass:
    @cached_property
    def value(self) -> dict[Any, Any]: ...
    def get(self, key, default=...) -> None: ...

PdfDefaultTTFMap = ...
_CallbackNames = ...

class PdfSysfontBase(pdfium_i.AutoCastable):
    SINGLETON = ...
    def __init__(self, default=...) -> None: ...
    def setup(self, reusable=...) -> None: ...
    def close(self, reusable=...) -> None: ...
    def Release(self, _) -> None: ...
    def EnumFonts(self, _, pMapper) -> Any: ...
    def MapFont(
        self, _, weight, bItalic, charset, pitch_family, face, _ignored
    ) -> Any: ...
    def GetFont(self, _, face) -> Any: ...
    def GetFontData(self, _, hFont, table, buffer, buf_size) -> Any: ...
    def GetFaceName(self, _, hFont, buffer, buf_size) -> Any: ...
    def GetFontCharset(self, _, hFont) -> Any: ...
    def DeleteFont(self, _, hFont) -> Any: ...
