from typing import Any
import ctypes

import pypdfium2.internal as pdfium_i

__all__ = ("PdfTextPage", "PdfTextSearcher")
c_double = ctypes.c_double
logger = ...

class PdfTextPage(pdfium_i.AutoCloseable):
    def __init__(self, raw, page) -> None: ...
    @property
    def parent(self) -> Any: ...
    def get_text_bounded(
        self, left=..., bottom=..., right=..., top=..., errors=...
    ) -> str: ...
    def get_text_range(self, index=..., count=..., errors=...) -> str: ...
    def count_chars(self) -> Any: ...
    def count_rects(self, index=..., count=...) -> Any: ...
    def get_index(self, x, y, x_tol, y_tol) -> None: ...
    def get_charbox(
        self, index, loose=...
    ) -> tuple[Any | float, Any | float, Any | float, Any | float]: ...
    def get_rect(self, index) -> tuple[float, float, float, float]: ...
    def get_textobj(self, index) -> PdfTextObj | None: ...
    def search(
        self,
        text,
        index=...,
        match_case=...,
        match_whole_word=...,
        consecutive=...,
        flags=...,
    ) -> PdfTextSearcher: ...

class PdfTextSearcher(pdfium_i.AutoCloseable):
    def __init__(self, raw, textpage) -> None: ...
    @property
    def parent(self) -> Any: ...
    def get_next(self) -> tuple[Any, Any] | None: ...
    def get_prev(self) -> tuple[Any, Any] | None: ...
