import pypdfium2.internal as pdfium_i

__all__ = ("PdfUnspHandler",)
lib_logger = ...

class PdfUnspHandler(pdfium_i.AutoCastable):
    SINGLETON = ...
    def __init__(self) -> None: ...
    def __call__(self, _, type) -> None: ...
    def setup(self, add_default=...) -> None: ...
