from transformers.image_processing_utils_fast import BaseImageProcessorFast
from transformers.utils import auto_docstring
from transformers.utils.import_utils import requires

"""Fast Image processor class for DINOv3."""
logger = ...

@auto_docstring
@requires(backends=("torchvision", "torch"))
class DINOv3ViTImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...

__all__ = ["DINOv3ViTImageProcessorFast"]
