from collections.abc import (
    Callable as Callable,
    Generator as Generator,
    Sequence as Sequence,
)
from contextlib import contextmanager as contextmanager
from datetime import timedelta as timedelta
from enum import Enum as Enum
from functools import partial as partial
from typing import (
    TYPE_CHECKING as TYPE_CHECKING,
    Any as Any,
    Literal as Literal,
    Union as Union,
    overload as overload,
)

from torch._C._autograd import DeviceType as DeviceType
from torch._C._distributed_c10d import (
    ProcessGroup as ProcessGroup,
    Work as _Work,
    _SymmetricMemory as _SymmetricMemory,
)
from torch.types import (
    _device as _device,
    _dtype as _dtype,
    _int as _int,
)

import torch
import torch.distributed.distributed_c10d as c10d

_group_name_to_store: dict[str, c10d.Store] = ...

def enable_symm_mem_for_group(group_name: str) -> None: ...

_is_test_mode: bool = ...
_mocked_group_names: set[str] | None = ...

def is_symm_mem_enabled_for_group(group_name: str) -> bool: ...

_group_name_to_workspace_tensor: dict[str, torch.Tensor | None] = ...

def get_symm_mem_workspace(group_name: str, min_size: int) -> _SymmetricMemory: ...

_backend_streams: dict[int, torch.cuda.Stream] = ...
lib = ...

class _ScaleMode(Enum):
    UNSCALED = ...
    TENSOR_WISE = ...
    ROW_WISE_SHARDED = ...
    ROW_WISE_REPLICATED = ...

def make_contiguous_for_perm(t: torch.Tensor, perm: list[int]) -> torch.Tensor: ...
def restride_A_shard_for_fused_all_gather_matmul(
    t: torch.Tensor, gather_dim: int
) -> torch.Tensor: ...
def restride_A_for_fused_matmul_reduce_scatter(
    t: torch.Tensor, scatter_dim: int
) -> torch.Tensor: ...

class Work(_Work):
    def __init__(self) -> None: ...
    def wait(self, timeout: timedelta = ...) -> bool: ...

@overload
def empty(
    *size: _int, dtype: _dtype | None = ..., device: _device | None = ...
) -> torch.Tensor: ...
@overload
def empty(
    size: Sequence[_int], *, dtype: _dtype | None = ..., device: _device | None = ...
) -> torch.Tensor: ...
def empty(
    *size: Any, dtype: _dtype | None = ..., device: _device | None = ...
) -> torch.Tensor: ...
def rendezvous(tensor: torch.Tensor, group: str | ProcessGroup) -> _SymmetricMemory: ...
def is_nvshmem_available() -> bool: ...
def set_backend(name: Literal["NVSHMEM", "CUDA", "NCCL"]) -> None: ...
def get_backend(device: _device) -> str | None: ...
def get_mempool_allocator(device: _device) -> Any: ...

__all__ = ["empty", "get_backend", "is_nvshmem_available", "rendezvous", "set_backend"]
