from ...processing_utils import Unpack, VideosKwargs
from ...video_processing_utils import BaseVideoProcessor

"""Video processor class for LLaVa-Onevision."""

class LlavaOnevisionFastVideoProcessorInitKwargs(VideosKwargs): ...

class LlavaOnevisionVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    rescale_factor = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_sample_frames = ...
    valid_kwargs = LlavaOnevisionFastVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(
        self, **kwargs: Unpack[LlavaOnevisionFastVideoProcessorInitKwargs]
    ) -> None: ...

__all__ = ["LlavaOnevisionVideoProcessor"]
