from transformers.models.detr.image_processing_detr_fast import DetrImageProcessorFast

from .modeling_grounding_dino import GroundingDinoObjectDetectionOutput
from ...utils import TensorType

logger = ...

class GroundingDinoImageProcessorFast(DetrImageProcessorFast):
    def post_process_object_detection(
        self,
        outputs: GroundingDinoObjectDetectionOutput,
        threshold: float = ...,
        target_sizes: TensorType | list[tuple] | None = ...,
    ):  # -> list[Any]:
        ...
    def post_process(self): ...
    def post_process_segmentation(self): ...
    def post_process_instance(self): ...
    def post_process_panoptic(self): ...
    def post_process_instance_segmentation(self): ...
    def post_process_semantic_segmentation(self): ...
    def post_process_panoptic_segmentation(self): ...

__all__ = ["GroundingDinoImageProcessorFast"]
