from contextlib import contextmanager as contextmanager
from typing import TYPE_CHECKING as TYPE_CHECKING

from torch.backends import (
    ContextProp as ContextProp,
    PropModule as PropModule,
    __allow_nonbracketed_mutation as __allow_nonbracketed_mutation,
    _FP32Precision as _FP32Precision,
    _get_fp32_precision_getter as _get_fp32_precision_getter,
    _set_fp32_precision_setter as _set_fp32_precision_setter,
)

def is_available() -> bool: ...

VERBOSE_OFF = ...
VERBOSE_ON = ...
VERBOSE_ON_CREATION = ...

class verbose:
    def __init__(self, level) -> None: ...
    def __enter__(self) -> Self | None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> Literal[False]: ...

def set_flags(
    _enabled=..., _deterministic=..., _allow_tf32=..., _fp32_precision=...
) -> tuple[bool, bool, bool, str]: ...
@contextmanager
def flags(
    enabled=..., deterministic=..., allow_tf32=..., fp32_precision=...
) -> Generator[None, Any, None]: ...

class MkldnnModule(PropModule):
    def __init__(self, m, name) -> None: ...
    def is_available(self) -> bool: ...

    enabled = ...
    deterministic = ...
    allow_tf32 = ...
    matmul = ...
    conv = ...
    rnn = ...
    fp32_precision = ...

enabled: ContextProp
deterministic: ContextProp
allow_tf32: ContextProp
