class ErrorHandler:
    def initialize(self) -> None: ...
    def record_exception(self, e: BaseException) -> None: ...
    def override_error_code_in_rootcause_data(
        self,
        rootcause_error_file: str,
        rootcause_error: dict[str, object],
        error_code: int = ...,
    ) -> None: ...
    def dump_error_file(
        self, rootcause_error_file: str, error_code: int = ...
    ) -> None: ...
