from collections.abc import Iterator
from typing import TypeVar, overload

from _typeshed import SupportsWrite
from pygments.formatter import Formatter
from pygments.lexer import Lexer
from pygments.token import _TokenType

"""
This type stub file was generated by pyright.
"""
_T = TypeVar("_T", str, bytes)
__version__: str
__all__ = ["format", "highlight", "lex"]

def lex(code: str, lexer: Lexer) -> Iterator[tuple[_TokenType, str]]: ...
@overload
def format(tokens, formatter: Formatter[_T], outfile: SupportsWrite[_T]) -> None: ...
@overload
def format(tokens, formatter: Formatter[_T], outfile: None = ...) -> _T: ...
@overload
def highlight(
    code: str, lexer: Lexer, formatter: Formatter[_T], outfile: SupportsWrite[_T]
) -> None: ...
@overload
def highlight(
    code: str, lexer: Lexer, formatter: Formatter[_T], outfile: None = ...
) -> _T: ...
