import argparse

"""
This type stub file was generated by pyright.
"""

def main_inner(parser, argns): ...

class HelpFormatter(argparse.HelpFormatter):
    def __init__(
        self, prog, indent_increment: int = ..., max_help_position: int = ..., width=...
    ) -> None: ...

def main(args=...): ...
