from _typeshed import Incomplete

"""
This type stub file was generated by pyright.
"""
esc: str
codes: Incomplete
dark_colors: Incomplete
light_colors: Incomplete

def reset_color(): ...
def colorize(color_key, text): ...
def ansiformat(attr, text): ...
