from collections.abc import Iterable, Iterator

from _typeshed import Incomplete
from pygments.lexer import Lexer
from pygments.token import _TokenType

"""
This type stub file was generated by pyright.
"""

def apply_filters(stream, filters, lexer=...): ...
def simplefilter(f): ...

class Filter:
    options: Incomplete
    def __init__(self, **options) -> None: ...
    def filter(
        self, lexer: Lexer, stream: Iterable[tuple[_TokenType, str]]
    ) -> Iterator[tuple[_TokenType, str]]: ...

class FunctionFilter(Filter):
    function: Incomplete
    def __init__(self, **options) -> None: ...
    def filter(
        self, lexer: Lexer, stream: Iterable[tuple[_TokenType, str]]
    ) -> Iterator[tuple[_TokenType, str]]: ...
