from typing import Generic, TypeVar, overload

from _typeshed import Incomplete

"""
This type stub file was generated by pyright.
"""
_T = TypeVar("_T", str, bytes)

class Formatter(Generic[_T]):
    name: Incomplete
    aliases: Incomplete
    filenames: Incomplete
    unicodeoutput: bool
    style: Incomplete
    full: Incomplete
    title: Incomplete
    encoding: Incomplete
    options: Incomplete
    @overload
    def __init__(
        self: Formatter[str],
        *,
        encoding: None = ...,
        outencoding: None = ...,
        **options,
    ) -> None: ...
    @overload
    def __init__(
        self: Formatter[bytes], *, encoding: str, outencoding: None = ..., **options
    ) -> None: ...
    @overload
    def __init__(
        self: Formatter[bytes], *, encoding: None = ..., outencoding: str, **options
    ) -> None: ...
    def get_style_defs(self, arg: str = ...): ...
    def format(self, tokensource, outfile): ...
