from _typeshed import Incomplete

"""
This type stub file was generated by pyright.
"""
CS_ESCAPE: Incomplete
FIRST_ELEMENT: Incomplete

def make_charset(letters): ...
def regex_opt_inner(strings, open_paren): ...
def regex_opt(strings, prefix: str = ..., suffix: str = ...): ...
