from typing import Any

import torch

class ModuleToTrace(torch.nn.Module):
    def __init__(self, foo: Any, in_spec: Any) -> None: ...
    def forward(self, *flat_args: Any) -> ExportTracerOutput: ...
    def __call__(self, *args: Any, **kwargs: Any) -> ExportTracerOutput: ...

ExportTracerOutput = ...
