from torchvision.transforms.v2 import functional as F

import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput, SizeDict
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for Nougat."""

class NougatFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_crop_margin: bool | None
    do_thumbnail: bool | None
    do_align_long_axis: bool | None

@auto_docstring
class NougatImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize: bool = ...
    do_normalize: bool = ...
    do_thumbnail: bool = ...
    do_align_long_axis: bool = ...
    do_pad: bool = ...
    do_rescale = ...
    do_crop_margin: bool = ...
    valid_kwargs = NougatFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[NougatFastImageProcessorKwargs]) -> None: ...
    @auto_docstring
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[NougatFastImageProcessorKwargs]
    ) -> BatchFeature: ...
    def python_find_non_zero(self, image: torch.Tensor):  # -> Tensor:
        ...
    def python_bounding_rect(self, coordinates):  # -> tuple[Any, Any, Any, Any]:
        ...
    def crop_margin(
        self, image: torch.Tensor, gray_threshold: int = ...
    ) -> torch.Tensor: ...
    def align_long_axis(self, image: torch.Tensor, size: SizeDict) -> torch.Tensor: ...
    def thumbnail(self, image: torch.Tensor, size: SizeDict) -> torch.Tensor: ...
    def pad_images(self, image: torch.Tensor, size: SizeDict) -> torch.Tensor: ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode | None = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...

__all__ = ["NougatImageProcessorFast"]
