from dataclasses import dataclass
from enum import Enum

import torch

from ...utils.metrics import traced

logger = ...

@staticmethod
def get_device_and_memory_breakdown() -> tuple[torch.device, int, int, int]: ...

class RequestStatus(Enum):
    PENDING = ...
    PREFILLING = ...
    PREFILLING_SPLIT = ...
    SPLIT_PENDING_REMAINDER = ...
    DECODING = ...
    FINISHED = ...
    FAILED = ...

@dataclass
class GenerationOutput:
    request_id: str
    prompt_ids: list[int] = ...
    generated_tokens: list[int] = ...
    logprobs: list[float] = ...
    error: str | None = ...
    status: RequestStatus = ...
    created_time: float = ...

@dataclass
class RequestState:
    request_id: str
    full_prompt_ids: list[int] | None = ...
    prompt_ids: list[int] | None = ...
    remaining_prompt_ids: list[int] = ...
    static_outputs: list[int] = ...
    allocated_blocks: int = ...
    position_offset: int = ...
    _status: RequestStatus = ...
    max_new_tokens: int = ...
    eos_token_id: int = ...
    created_time: float = ...
    error: str | None = ...
    lifespan: tuple[float, float] = ...
    @property
    def status(self) -> RequestStatus: ...
    @status.setter
    def status(self, value: RequestStatus):  # -> None:
        ...
    def log_end_of_request(self):  # -> None:
        ...
    def current_len(self) -> int: ...
    def generated_len(self) -> int: ...
    @traced
    def update_with_token(self, token_id: int) -> bool: ...
    def __repr__(self):  # -> str:
        ...
    def to_generation_output(self):  # -> GenerationOutput:
        ...
