from torch.utils._ordered_set import OrderedSet

import torch

aten = ...

class NumpyCompatNormalization:
    numpy_compat: dict[str, tuple[str, ...]] = ...
    inverse_mapping: dict[str, str]
    cache: dict[torch.fx.graph.Target, OrderedSet[str]]
    def __init__(self) -> None: ...
    def __call__(self, graph: torch.fx.Graph) -> None: ...

numpy_compat_normalization = ...
