from torchvision.transforms.v2 import functional as F

import torch

from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import PILImageResampling, SizeDict
from ...processing_utils import Unpack
from ...utils import auto_docstring

class DeepseekVLHybridFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    min_size: int
    high_res_size: dict
    high_res_resample: PILImageResampling
    high_res_image_mean: list[float]
    high_res_image_std: list[float]

@auto_docstring
class DeepseekVLHybridImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    min_size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_pad = ...
    valid_kwargs = DeepseekVLHybridFastImageProcessorKwargs
    high_res_image_mean = ...
    high_res_image_std = ...
    high_res_size = ...
    high_res_resample = ...
    model_input_names = ...
    def __init__(
        self, **kwargs: Unpack[DeepseekVLHybridFastImageProcessorKwargs]
    ) -> None: ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        min_size: int,
        interpolation: F.InterpolationMode | None = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...
    def pad_to_square(
        self,
        images: torch.Tensor,
        background_color: int | tuple[int, int, int] = ...,
    ) -> torch.Tensor: ...

__all__ = ["DeepseekVLHybridImageProcessorFast"]
