from typing import Any, Self

import torch

__all__ = ["Linear"]

class Linear(torch.nn.Module):
    _op_type = ...
    _FLOAT_MODULE = torch.nn.Linear
    def __init__(
        self,
        in_features,
        out_features,
        row_block_size,
        col_block_size,
        bias=...,
        dtype=...,
    ) -> None: ...
    def extra_repr(self) -> str: ...
    def __repr__(self): ...
    def forward(self, x: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...
    def weight(self) -> Any: ...
    def bias(self) -> Any: ...
    def set_weight_bias(
        self,
        w: torch.Tensor,
        b: torch.Tensor | None,
        row_block_size: int | None,
        col_block_size: int | None,
    ) -> None: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...) -> Self: ...
