from typing import TypeVar

from _typeshed import Incomplete
from pygments.formatter import Formatter

"""
This type stub file was generated by pyright.
"""
_T = TypeVar("_T", str, bytes)

class PangoMarkupFormatter(Formatter[_T]):
    name: str
    aliases: Incomplete
    filenames: Incomplete
    styles: Incomplete
    def format_unencoded(self, tokensource, outfile) -> None: ...
