from torch import nn

import torch

from .configuration_audio_spectrogram_transformer import ASTConfig
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import (
    BaseModelOutput,
    BaseModelOutputWithPooling,
    SequenceClassifierOutput,
)
from ...modeling_utils import PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring
from ...utils.generic import can_return_tuple, check_model_inputs

"""PyTorch Audio Spectrogram Transformer (AST) model."""
logger = ...

class ASTEmbeddings(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def get_shape(self, config):  # -> tuple[Any, Any]:
        ...
    def forward(self, input_values: torch.Tensor) -> torch.Tensor: ...

class ASTPatchEmbeddings(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, input_values: torch.Tensor) -> torch.Tensor: ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class ASTSelfAttention(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> tuple[torch.Tensor, torch.Tensor]: ...

class ASTSelfOutput(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...

class ASTAttention(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def prune_heads(self, heads: set[int]):  # -> None:
        ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...

class ASTIntermediate(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class ASTOutput(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...

class ASTLayer(GradientCheckpointingLayer):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...

class ASTEncoder(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> BaseModelOutput: ...

@auto_docstring
class ASTPreTrainedModel(PreTrainedModel):
    config: ASTConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...
    _can_record_outputs = ...

@auto_docstring
class ASTModel(ASTPreTrainedModel):
    def __init__(self, config: ASTConfig) -> None: ...
    def get_input_embeddings(self) -> ASTPatchEmbeddings: ...
    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        input_values: torch.Tensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutputWithPooling: ...

class ASTMLPHead(nn.Module):
    def __init__(self, config: ASTConfig) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

@auto_docstring(custom_intro=...)
class ASTForAudioClassification(ASTPreTrainedModel):
    def __init__(self, config: ASTConfig) -> None: ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_values: torch.Tensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        labels: torch.Tensor | None = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> SequenceClassifierOutput: ...

__all__ = ["ASTForAudioClassification", "ASTModel", "ASTPreTrainedModel"]
