Entry = ...

def update_hash(seed, value): ...
def hash_source_files(hash_value, source_files): ...
def hash_build_arguments(hash_value, build_arguments): ...

class ExtensionVersioner:
    def __init__(self) -> None: ...
    def get_version(self, name) -> None: ...
    def bump_version_if_changed(
        self,
        name,
        source_files,
        build_arguments,
        build_directory,
        with_cuda,
        with_sycl,
        is_python_module,
        is_standalone,
    ): ...
