import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for SigLIP2."""
logger = ...

def convert_image_to_patches(image: torch.Tensor, patch_size: int) -> torch.Tensor: ...
def pad_along_first_dim(
    tensor: torch.Tensor, target_length: int, pad_value: int = ...
) -> tuple[torch.Tensor, torch.Tensor]: ...

class Siglip2FastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    patch_size: int | None
    max_num_patches: int | None

@auto_docstring
class Siglip2ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    patch_size = ...
    max_num_patches = ...
    valid_kwargs = Siglip2FastImageProcessorKwargs
    unused_kwargs = ...
    def __init__(self, **kwargs: Unpack[Siglip2FastImageProcessorKwargs]) -> None: ...
    @auto_docstring
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[Siglip2FastImageProcessorKwargs]
    ) -> BatchFeature: ...

__all__ = ["Siglip2ImageProcessorFast"]
