from collections.abc import Callable
from threading import Event, Thread

class IntervalRunner:
    event: Event
    thread: Thread
    def __init__(
        self, target: Callable[[], None], interval_seconds: float = ...
    ) -> None: ...
    def start(self) -> IntervalRunner: ...
    def is_alive(self) -> bool: ...
    def shutdown(self) -> None: ...
