from slack_sdk.models import JsonObject

class SocketModeResponse:
    envelope_id: str
    payload: dict | None
    def __init__(
        self, envelope_id: str, payload: dict | JsonObject | str | None = ...
    ) -> None: ...
    def to_dict(self) -> dict: ...
