from ...processing_utils import ProcessorMixin

"""
Text/audio processor class for MusicGen
"""

class MusicgenProcessor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __init__(self, feature_extractor, tokenizer) -> None: ...
    def get_decoder_prompt_ids(self, task=..., language=..., no_timestamps=...): ...
    def __call__(self, *args, **kwargs):  # -> BatchFeature:
        ...
    def batch_decode(self, *args, **kwargs):  # -> list[ndarray[Any, Any]]:
        ...

__all__ = ["MusicgenProcessor"]
