from .modeling_owlvit import OwlViTObjectDetectionOutput
from ...image_processing_utils_fast import BaseImageProcessorFast
from ...utils import TensorType, auto_docstring

"""Fast Image processor class for OwlViT"""
logger = ...

@auto_docstring
class OwlViTImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    model_input_names = ...
    def post_process(self, outputs, target_sizes):  # -> list[dict[str, Tensor | str]]:
        ...
    def post_process_object_detection(
        self,
        outputs: OwlViTObjectDetectionOutput,
        threshold: float = ...,
        target_sizes: TensorType | list[tuple] | None = ...,
    ):  # -> list[Any]:
        ...
    def post_process_image_guided_detection(
        self, outputs, threshold=..., nms_threshold=..., target_sizes=...
    ):  # -> list[Any]:
        ...

__all__ = ["OwlViTImageProcessorFast"]
