from collections.abc import Iterable

import torch

_MISSING: torch.Tensor = ...

def set_tensor(module: torch.nn.Module, name: str, tensor: torch.Tensor) -> None: ...
def swap_tensor(
    module: torch.nn.Module, name: str, tensor: torch.Tensor, allow_missing: bool = ...
) -> torch.Tensor: ...
def swap_submodule(
    module: torch.nn.Module, name: str, submodule: torch.nn.Module
) -> torch.nn.Module: ...

class NamedMemberAccessor:
    def __init__(self, module: torch.nn.Module) -> None: ...
    def get_submodule(self, name: str) -> torch.nn.Module: ...
    def swap_submodule(self, path: str, value: torch.nn.Module) -> torch.nn.Module: ...
    def get_tensor(self, name: str) -> torch.Tensor: ...
    def set_tensor(self, name: str, value: torch.Tensor) -> None: ...
    def del_tensor(self, name: str) -> None: ...
    def swap_tensor(
        self, name: str, value: torch.Tensor, allow_missing: bool = ...
    ) -> torch.Tensor: ...
    def get_tensors(self, names: Iterable[str]) -> list[torch.Tensor]: ...
    def set_tensors(
        self, names: Iterable[str], values: Iterable[torch.Tensor]
    ) -> None: ...
    def set_tensors_dict(self, named_tensors: dict[str, torch.Tensor]) -> None: ...
    def del_tensors(self, names: Iterable[str]) -> None: ...
    def swap_tensors(
        self,
        names: Iterable[str],
        values: Iterable[torch.Tensor],
        allow_missing: bool = ...,
    ) -> list[torch.Tensor]: ...
    def swap_tensors_dict(
        self, named_tensors: dict[str, torch.Tensor], allow_missing: bool = ...
    ) -> tuple[dict[str, torch.Tensor], list[str]]: ...
    def check_keys(self, keys: Iterable[str]) -> tuple[list[str], list[str]]: ...
    def named_parameters(
        self, remove_duplicate: bool = ...
    ) -> Iterable[tuple[str, torch.Tensor]]: ...
    def named_buffers(
        self, remove_duplicate: bool = ...
    ) -> Iterable[tuple[str, torch.Tensor]]: ...
    def named_tensors(
        self, remove_duplicate: bool = ...
    ) -> Iterable[tuple[str, torch.Tensor]]: ...
    def named_modules(
        self, remove_duplicate: bool = ...
    ) -> Iterable[tuple[str, torch.nn.Module]]: ...
