from transformers.models.detr.image_processing_detr_fast import DetrImageProcessorFast

from ...utils import TensorType

logger = ...

def get_size_with_aspect_ratio(
    image_size: tuple[int, int],
    size: int,
    max_size: int | None = ...,
    mod_size: int = ...,
) -> tuple[int, int]: ...

class YolosImageProcessorFast(DetrImageProcessorFast):
    def post_process(self, outputs, target_sizes):  # -> list[dict[str, Tensor | Any]]:
        ...
    def post_process_object_detection(
        self,
        outputs,
        threshold: float = ...,
        target_sizes: TensorType | list[tuple] = ...,
        top_k: int = ...,
    ):  # -> list[Any]:
        ...
    def post_process_segmentation(self): ...
    def post_process_instance(self): ...
    def post_process_panoptic(self): ...
    def post_process_instance_segmentation(self): ...
    def post_process_semantic_segmentation(self): ...
    def post_process_panoptic_segmentation(self): ...

__all__ = ["YolosImageProcessorFast"]
