from typing import Literal

import enum

from torch._C import _onnx as _C_onnx

import torch

"""Utilities for converting and operating on ONNX, JIT and torch types."""
type ScalarName = Literal[
    "Byte",
    "Char",
    "Double",
    "Float",
    "Half",
    "Int",
    "Long",
    "Short",
    "Bool",
    "ComplexHalf",
    "ComplexFloat",
    "ComplexDouble",
    "QInt8",
    "QUInt8",
    "QInt32",
    "BFloat16",
    "Float8E5M2",
    "Float8E4M3FN",
    "Float8E5M2FNUZ",
    "Float8E4M3FNUZ",
    "Undefined",
]
type TorchName = Literal[
    "bool",
    "uint8_t",
    "int8_t",
    "double",
    "float",
    "half",
    "int",
    "int64_t",
    "int16_t",
    "complex32",
    "complex64",
    "complex128",
    "qint8",
    "quint8",
    "qint32",
    "bfloat16",
    "float8_e5m2",
    "float8_e4m3fn",
    "float8_e5m2fnuz",
    "float8_e4m3fnuz",
]

class JitScalarType(enum.IntEnum):
    UINT8 = ...
    INT8 = ...
    INT16 = ...
    INT = ...
    INT64 = ...
    HALF = ...
    FLOAT = ...
    DOUBLE = ...
    COMPLEX32 = ...
    COMPLEX64 = ...
    COMPLEX128 = ...
    BOOL = ...
    QINT8 = ...
    QUINT8 = ...
    QINT32 = ...
    BFLOAT16 = ...
    FLOAT8E5M2 = ...
    FLOAT8E4M3FN = ...
    FLOAT8E5M2FNUZ = ...
    FLOAT8E4M3FNUZ = ...
    UNDEFINED = ...
    @classmethod
    def from_dtype(cls, dtype: torch.dtype | None) -> JitScalarType: ...
    @classmethod
    def from_onnx_type(
        cls, onnx_type: int | _C_onnx.TensorProtoDataType | None
    ) -> JitScalarType: ...
    @classmethod
    def from_value(
        cls, value: torch._C.Value | torch.Tensor | None, default=...
    ) -> JitScalarType: ...
    def scalar_name(self) -> ScalarName: ...
    def torch_name(self) -> TorchName: ...
    def dtype(self) -> torch.dtype: ...
    def onnx_type(self) -> _C_onnx.TensorProtoDataType: ...
    def onnx_compatible(self) -> bool: ...

def valid_scalar_name(scalar_name: ScalarName | str) -> bool: ...
def valid_torch_name(torch_name: TorchName | str) -> bool: ...

_SCALAR_TYPE_TO_NAME: dict[JitScalarType, ScalarName] = ...
_SCALAR_NAME_TO_TYPE: dict[ScalarName, JitScalarType] = ...
_SCALAR_TYPE_TO_TORCH_NAME: dict[JitScalarType, TorchName] = ...
_TORCH_NAME_TO_SCALAR_TYPE: dict[TorchName, JitScalarType] = ...
_SCALAR_TYPE_TO_ONNX = ...
_ONNX_TO_SCALAR_TYPE = ...
_SCALAR_TYPE_TO_DTYPE = ...
_DTYPE_TO_SCALAR_TYPE = ...
