from collections.abc import Iterator
from collections.abc import Callable, Collection, Sequence
from typing import Generic, TypeVar
from typing_extensions import ParamSpec

"""Module for handling symbolic function registration."""
OpsetVersion = int
_K = TypeVar("_K")
_V = TypeVar("_V")
_R = TypeVar("_R")
_P = ParamSpec("_P")

class OverrideDict(Collection[_K], Generic[_K, _V]):
    def __init__(self) -> None: ...
    def set_base(self, key: _K, value: _V) -> None: ...
    def in_base(self, key: _K) -> bool: ...
    def override(self, key: _K, value: _V) -> None: ...
    def remove_override(self, key: _K) -> None: ...
    def overridden(self, key: _K) -> bool: ...
    def __getitem__(self, key: _K) -> _V: ...
    def get(self, key: _K, default: _V | None = ...) -> _V | None: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[_K]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...

class _SymbolicFunctionGroup:
    def __init__(self, name: str) -> None: ...
    def __getitem__(self, key: OpsetVersion) -> Callable: ...
    def get(self, opset: OpsetVersion) -> Callable | None: ...
    def add(self, func: Callable, opset: OpsetVersion) -> None: ...
    def add_custom(self, func: Callable, opset: OpsetVersion) -> None: ...
    def remove_custom(self, opset: OpsetVersion) -> None: ...
    def get_min_supported(self) -> OpsetVersion: ...

class SymbolicRegistry:
    def __init__(self) -> None: ...
    def register(
        self, name: str, opset: OpsetVersion, func: Callable, custom: bool = ...
    ) -> None: ...
    def unregister(self, name: str, opset: OpsetVersion) -> None: ...
    def get_function_group(self, name: str) -> _SymbolicFunctionGroup | None: ...
    def is_registered_op(self, name: str, version: int) -> bool: ...
    def all_functions(self) -> set[str]: ...

def onnx_symbolic(
    name: str,
    opset: OpsetVersion | Sequence[OpsetVersion],
    decorate: Sequence[Callable] | None = ...,
    custom: bool = ...,
) -> Callable: ...
def custom_onnx_symbolic(
    name: str,
    opset: OpsetVersion | Sequence[OpsetVersion],
    decorate: Sequence[Callable] | None = ...,
) -> Callable: ...

registry = ...
