import torch
import torch.distributed as dist

class DefaultState:
    __slots__ = ...
    def __init__(self, process_group: dist.ProcessGroup) -> None: ...

class LowPrecisionState(DefaultState):
    __slots__ = ...
    def __init__(self, process_group, parameter_type=...) -> None: ...

def allreduce_hook(state: DefaultState, grad: torch.Tensor) -> None: ...
def reduce_scatter_hook(
    state: DefaultState, grad: torch.Tensor, output: torch.Tensor
) -> None: ...
def fp16_compress_hook(
    state: LowPrecisionState, grad: torch.Tensor, output: torch.Tensor | None = ...
) -> None: ...
def bf16_compress_hook(
    state: LowPrecisionState, grad: torch.Tensor, output: torch.Tensor | None = ...
) -> None: ...
