from torchvision.transforms.v2 import functional as F

import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput, SizeDict
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for TVP."""

class TvpFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_flip_channel_order: bool | None
    constant_values: float | list[float] | None
    pad_mode: str | None

@auto_docstring
class TvpImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    rescale_factor = ...
    do_pad = ...
    pad_size = ...
    constant_values = ...
    pad_mode = ...
    do_normalize = ...
    do_flip_channel_order = ...
    valid_kwargs = TvpFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[TvpFastImageProcessorKwargs]) -> None: ...
    @auto_docstring
    def preprocess(
        self,
        videos: ImageInput | list[ImageInput] | list[list[ImageInput]],
        **kwargs: Unpack[TvpFastImageProcessorKwargs],
    ) -> BatchFeature: ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode | None = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...

__all__ = ["TvpImageProcessorFast"]
