from ...processing_utils import Unpack, VideosKwargs
from ...utils import add_start_docstrings
from ...video_processing_utils import BASE_VIDEO_PROCESSOR_DOCSTRING, BaseVideoProcessor
from ...video_utils import VideoMetadata

"""video processor class for Qwen3-VL."""
logger = ...

def smart_resize(
    num_frames: int,
    height: int,
    width: int,
    temporal_factor: int = ...,
    factor: int = ...,
    min_pixels: int = ...,
    max_pixels: int = ...,
):  # -> tuple[int, int]:
    ...

class Qwen3VLVideoProcessorInitKwargs(VideosKwargs):
    patch_size: int | None
    temporal_patch_size: int | None
    merge_size: int | None
    min_frames: int | None
    max_frames: int | None

@add_start_docstrings(
    ...,
    BASE_VIDEO_PROCESSOR_DOCSTRING,
    ...,
)
class Qwen3VLVideoProcessor(BaseVideoProcessor):
    resample = ...
    size = ...
    image_mean = ...
    image_std = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    patch_size = ...
    temporal_patch_size = ...
    merge_size = ...
    fps = ...
    min_frames = ...
    max_frames = ...
    do_sample_frames = ...
    valid_kwargs = Qwen3VLVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[Qwen3VLVideoProcessorInitKwargs]) -> None: ...
    def sample_frames(
        self,
        metadata: VideoMetadata,
        num_frames: int | None = ...,
        fps: float | None = ...,
        **kwargs,
    ):  # -> NDArray[Any]:
        ...

__all__ = ["Qwen3VLVideoProcessor"]
