from collections.abc import Callable
from typing import Any, NamedTuple

from ._structures import InfinityType, NegativeInfinityType

"""
.. testsetup::

    from packaging.version import parse, Version
"""
__all__ = ["VERSION_PATTERN", "InvalidVersion", "Version", "parse"]
type LocalType = tuple[int | str, ...]
type CmpPrePostDevType = InfinityType | NegativeInfinityType | tuple[str, int]
type CmpLocalType = (
    NegativeInfinityType
    | tuple[tuple[int, str] | tuple[NegativeInfinityType, int | str], ...]
)
type CmpKey = tuple[
    int,
    tuple[int, ...],
    CmpPrePostDevType,
    CmpPrePostDevType,
    CmpPrePostDevType,
    CmpLocalType,
]
type VersionComparisonMethod = Callable[[CmpKey, CmpKey], bool]

class _Version(NamedTuple):
    epoch: int
    release: tuple[int, ...]
    dev: tuple[str, int] | None
    pre: tuple[str, int] | None
    post: tuple[str, int] | None
    local: LocalType | None

def parse(version: str) -> Version: ...

class InvalidVersion(ValueError): ...

class _BaseVersion:
    _key: tuple[Any, ...]
    def __hash__(self) -> int: ...
    def __lt__(self, other: _BaseVersion) -> bool: ...
    def __le__(self, other: _BaseVersion) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ge__(self, other: _BaseVersion) -> bool: ...
    def __gt__(self, other: _BaseVersion) -> bool: ...
    def __ne__(self, other: object) -> bool: ...

_VERSION_PATTERN = ...
VERSION_PATTERN = ...

class Version(_BaseVersion):
    _regex = ...
    _key: CmpKey
    def __init__(self, version: str) -> None: ...
    @property
    def epoch(self) -> int: ...
    @property
    def release(self) -> tuple[int, ...]: ...
    @property
    def pre(self) -> tuple[str, int] | None: ...
    @property
    def post(self) -> int | None: ...
    @property
    def dev(self) -> int | None: ...
    @property
    def local(self) -> str | None: ...
    @property
    def public(self) -> str: ...
    @property
    def base_version(self) -> str: ...
    @property
    def is_prerelease(self) -> bool: ...
    @property
    def is_postrelease(self) -> bool: ...
    @property
    def is_devrelease(self) -> bool: ...
    @property
    def major(self) -> int: ...
    @property
    def minor(self) -> int: ...
    @property
    def micro(self) -> int: ...

_local_version_separators = ...
