from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Any

from torch.distributed.fsdp import FullyShardedDataParallel
from torch.nn.parallel import DistributedDataParallel
from torch.optim import Optimizer

_registered_overlapped_optims: dict[type, type] = ...

def register_overlapped(optim_cls) -> Callable[..., Any]: ...

class OverlappedOptimizer(ABC):
    def __init__(self, optim_cls: type) -> None: ...
    @abstractmethod
    def register_ddp(self, ddp: DistributedDataParallel) -> None: ...
    @abstractmethod
    def register_fsdp(self, fsdp: FullyShardedDataParallel) -> None: ...

@register_overlapped(Optimizer)
class _OverlappedStandardOptimizer(OverlappedOptimizer):
    def __init__(
        self, optim_cls: type, params, *optim_args, **optim_kwargs
    ) -> None: ...
    def register_ddp(self, ddp_inst: DistributedDataParallel) -> None: ...
    def register_fsdp(self, fsdp: FullyShardedDataParallel) -> None: ...
