from dataclasses import dataclass
from typing import Any

from torch import nn

import torch

from .configuration_vit_mae import ViTMAEConfig
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput
from ...modeling_utils import PreTrainedModel
from ...processing_utils import Unpack
from ...utils import ModelOutput, TransformersKwargs, auto_docstring
from ...utils.generic import can_return_tuple, check_model_inputs

"""PyTorch ViT MAE (masked autoencoder) model."""
logger = ...

@dataclass
@auto_docstring(custom_intro=...)
class ViTMAEModelOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    mask: torch.LongTensor | None = ...
    ids_restore: torch.LongTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

@dataclass
@auto_docstring(custom_intro=...)
class ViTMAEDecoderOutput(ModelOutput):
    logits: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

@dataclass
@auto_docstring(custom_intro=...)
class ViTMAEForPreTrainingOutput(ModelOutput):
    loss: torch.FloatTensor | None = ...
    logits: torch.FloatTensor | None = ...
    mask: torch.LongTensor | None = ...
    ids_restore: torch.LongTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

def get_2d_sincos_pos_embed(
    embed_dim, grid_size, add_cls_token=...
):  # -> NDArray[float64] | NDArray[Any]:
    ...
def get_2d_sincos_pos_embed_from_grid(embed_dim, grid):  # -> NDArray[Any]:
    ...
def get_1d_sincos_pos_embed_from_grid(embed_dim, pos):  # -> NDArray[Any]:
    ...

class ViTMAEEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def initialize_weights(self):  # -> None:
        ...
    def interpolate_pos_encoding(
        self, embeddings: torch.Tensor, height: int, width: int
    ) -> torch.Tensor: ...
    def random_masking(self, sequence, noise=...):  # -> tuple[Tensor, Tensor, Tensor]:
        ...
    def forward(
        self, pixel_values, noise=..., interpolate_pos_encoding: bool = ...
    ):  # -> tuple[Tensor, Tensor, Tensor]:
        ...

class ViTMAEPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values, interpolate_pos_encoding: bool = ...):  # -> Any:
        ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class ViTMAESelfAttention(nn.Module):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> tuple[torch.Tensor, torch.Tensor]: ...

class ViTMAESelfOutput(nn.Module):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class ViTMAEAttention(nn.Module):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def prune_heads(self, heads: set[int]):  # -> None:
        ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class ViTMAEIntermediate(nn.Module):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class ViTMAEOutput(nn.Module):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class ViTMAELayer(GradientCheckpointingLayer):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class ViTMAEEncoder(nn.Module):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> BaseModelOutput: ...
    def __call__(self, *args: Any, **kwargs: Any) -> BaseModelOutput: ...

@auto_docstring
class ViTMAEPreTrainedModel(PreTrainedModel):
    config: ViTMAEConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...
    _can_record_outputs = ...

@auto_docstring
class ViTMAEModel(ViTMAEPreTrainedModel):
    def __init__(self, config) -> None: ...
    def get_input_embeddings(self):  # -> ViTMAEPatchEmbeddings:
        ...
    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        noise: torch.FloatTensor | None = ...,
        head_mask: torch.FloatTensor | None = ...,
        interpolate_pos_encoding: bool = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> ViTMAEModelOutput: ...

class ViTMAEDecoder(nn.Module):
    def __init__(self, config: ViTMAEConfig, num_patches: int) -> None: ...
    def interpolate_pos_encoding(self, embeddings: torch.Tensor) -> torch.Tensor: ...
    def initialize_weights(self, num_patches):  # -> None:
        ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        ids_restore: torch.Tensor,
        interpolate_pos_encoding: bool = ...,
    ):  # -> ViTMAEDecoderOutput:
        ...

@auto_docstring(custom_intro=...)
class ViTMAEForPreTraining(ViTMAEPreTrainedModel):
    def __init__(self, config: ViTMAEConfig) -> None: ...
    def get_input_embeddings(self):  # -> ViTMAEPatchEmbeddings:
        ...
    def patchify(
        self, pixel_values, interpolate_pos_encoding: bool = ...
    ):  # -> Tensor:
        ...
    def unpatchify(
        self,
        patchified_pixel_values,
        original_image_size: tuple[int, int] | None = ...,
    ):  # -> Tensor:
        ...
    def forward_loss(
        self, pixel_values, pred, mask, interpolate_pos_encoding: bool = ...
    ): ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        noise: torch.FloatTensor | None = ...,
        head_mask: torch.FloatTensor | None = ...,
        interpolate_pos_encoding: bool = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> ViTMAEForPreTrainingOutput: ...

__all__ = [
    "ViTMAEForPreTraining",
    "ViTMAELayer",
    "ViTMAEModel",
    "ViTMAEPreTrainedModel",
]
