from typing import Self

"""A Python module for interacting and consuming responses from Slack."""

class AsyncSlackResponse:
    def __init__(
        self,
        *,
        client,
        http_verb: str,
        api_url: str,
        req_args: dict,
        data: dict | bytes,
        headers: dict,
        status_code: int,
    ) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> object: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> Self: ...
    def get(self, key: str, default: object = ...) -> object: ...
    def validate(self) -> Self: ...
