from typing import Self
from typing import Any, TypeVar, overload

"""A Python module for interacting and consuming responses from Slack."""
T = TypeVar("T")

class AsyncSlackResponse:
    def __init__(
        self,
        *,
        client,
        http_verb: str,
        api_url: str,
        req_args: dict,
        data: dict | bytes,
        headers: dict,
        status_code: int,
    ) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key) -> None: ...
    def __aiter__(self) -> Self: ...
    async def __anext__(self) -> Self: ...
    @overload
    def get(self, key: str, default: None = ...) -> None: ...
    @overload
    def get(self, key: str, default: T) -> T: ...
    def get(self, key, default=...) -> None: ...
    def validate(self) -> Self: ...
