from ...processing_utils import Unpack, VideosKwargs
from ...video_processing_utils import BaseVideoProcessor

"""
Video processor class for InstructBLIPVideo
"""

class InstructBlipVideoVideoProcessorInitKwargs(VideosKwargs): ...

class InstructBlipVideoVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_sample_frames = ...
    valid_kwargs = InstructBlipVideoVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(
        self, **kwargs: Unpack[InstructBlipVideoVideoProcessorInitKwargs]
    ) -> None: ...

__all__ = ["InstructBlipVideoVideoProcessor"]
