import pathlib

from transformers.models.detr.image_processing_detr_fast import (
    DetrFastImageProcessorKwargs,
    DetrImageProcessorFast,
)

import torch

from ...image_processing_utils import BatchFeature
from ...image_utils import (
    AnnotationFormat,
    AnnotationType,
    ChannelDimension,
    ImageInput,
)
from ...processing_utils import Unpack
from ...utils import TensorType

logger = ...
SUPPORTED_ANNOTATION_FORMATS = ...

def prepare_coco_detection_annotation(
    image,
    target,
    return_segmentation_masks: bool = ...,
    input_data_format: ChannelDimension | str | None = ...,
):  # -> dict[str, Tensor]:
    ...

class RTDetrFastImageProcessorKwargs(DetrFastImageProcessorKwargs): ...

class RTDetrImageProcessorFast(DetrImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    format = ...
    do_convert_annotations = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_pad = ...
    size = ...
    default_to_square = ...
    model_input_names = ...
    valid_kwargs = RTDetrFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[RTDetrFastImageProcessorKwargs]) -> None: ...
    def preprocess(
        self,
        images: ImageInput,
        annotations: AnnotationType | list[AnnotationType] | None = ...,
        masks_path: str | pathlib.Path | None = ...,
        **kwargs: Unpack[RTDetrFastImageProcessorKwargs],
    ) -> BatchFeature: ...
    def prepare_annotation(
        self,
        image: torch.Tensor,
        target: dict,
        format: AnnotationFormat | None = ...,
        return_segmentation_masks: bool | None = ...,
        masks_path: str | pathlib.Path | None = ...,
        input_data_format: str | ChannelDimension | None = ...,
    ) -> dict: ...
    def post_process_object_detection(
        self,
        outputs,
        threshold: float = ...,
        target_sizes: TensorType | list[tuple] = ...,
        use_focal_loss: bool = ...,
    ):  # -> list[Any]:
        ...
    def from_dict(self): ...
    def post_process(self): ...
    def post_process_segmentation(self): ...
    def post_process_instance(self): ...
    def post_process_panoptic(self): ...
    def post_process_instance_segmentation(self): ...
    def post_process_semantic_segmentation(self): ...
    def post_process_panoptic_segmentation(self): ...

__all__ = ["RTDetrImageProcessorFast"]
