from collections.abc import Mapping

from slack_sdk.web.async_slack_response import AsyncSlackResponse

class SlackClientError(Exception): ...
class BotUserAccessError(SlackClientError): ...
class SlackRequestError(SlackClientError): ...

class SlackApiError(SlackClientError):
    response: AsyncSlackResponse | Mapping[str, object]
    def __init__(
        self,
        message: str,
        response: AsyncSlackResponse | Mapping[str, object],
    ) -> None: ...

class SlackTokenRotationError(SlackClientError):
    api_error: SlackApiError
    def __init__(self, api_error: SlackApiError) -> None: ...

class SlackClientNotConnectedError(SlackClientError): ...
class SlackObjectFormationError(SlackClientError): ...
class SlackClientConfigurationError(SlackClientError): ...
