import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for MobileNetV2."""

class MobileNetV2FastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    do_reduce_labels: bool | None

@auto_docstring
class MobileNetV2ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_reduce_labels = ...
    valid_kwargs = MobileNetV2FastImageProcessorKwargs
    def __init__(
        self, **kwargs: Unpack[MobileNetV2FastImageProcessorKwargs]
    ) -> None: ...
    def reduce_label(self, labels: list[torch.Tensor]):  # -> Tensor:
        ...
    @auto_docstring
    def preprocess(
        self,
        images: ImageInput,
        segmentation_maps: ImageInput | None = ...,
        **kwargs: Unpack[MobileNetV2FastImageProcessorKwargs],
    ) -> BatchFeature: ...
    def post_process_semantic_segmentation(
        self, outputs, target_sizes: list[tuple] | None = ...
    ):  # -> list[Any]:
        ...

__all__ = ["MobileNetV2ImageProcessorFast"]
