from collections.abc import Iterator
from contextlib import contextmanager
from enum import StrEnum

logger = ...

class SimpleProfiler:
    class Type(StrEnum):
        ALL = ...
        ALLGATHER = ...
        ALLGATHER_OBJ = ...
        RESHARDING = ...
        H2D = ...
        D2H = ...

    results: dict[str, float] = ...
    profiling: set[str] = ...
    @classmethod
    def reset(cls) -> None: ...
    @classmethod
    @contextmanager
    def profile(cls, profile_type: str) -> Iterator[None]: ...
    @classmethod
    def dump_and_reset(cls, msg: str) -> None: ...
