import torch.distributed as dist

_TORCHDISTX_AVAIL = ...
PARAM_BROADCAST_BUCKET_SIZE = ...
FSDP_SYNCED = ...
type HybridShardProcessGroupType = tuple[dist.ProcessGroup, dist.ProcessGroup]
type ProcessGroupType = dist.ProcessGroup | HybridShardProcessGroupType | None
SHARDING_STRATEGY_MAP = ...
HYBRID_SHARDING_STRATEGIES = ...
NO_RESHARD_AFTER_FORWARD_STRATEGIES = ...
