from abc import ABC, abstractmethod
from typing import Any

from torch.nn import ModuleList

import torch

from ..modeling_utils import PreTrainedModel
from ..utils import is_torch_available
from ..utils.quantization_config import QuantizationConfigMixin

if is_torch_available(): ...
else:
    ModuleList = ...
logger = ...

class HfQuantizer(ABC):
    requires_calibration = ...
    required_packages = ...
    requires_parameters_quantization = ...
    def __init__(
        self, quantization_config: QuantizationConfigMixin, **kwargs
    ) -> None: ...
    def update_torch_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def update_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def update_device_map(
        self, device_map: dict[str, Any] | None
    ) -> dict[str, Any] | None: ...
    def adjust_target_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def update_missing_keys(
        self, model, missing_keys: list[str], prefix: str
    ) -> list[str]: ...
    def update_expected_keys(
        self, model, expected_keys: list[str], loaded_keys: list[str]
    ) -> list[str]: ...
    def update_unexpected_keys(
        self, model, unexpected_keys: list[str]
    ) -> list[str]: ...
    def get_special_dtypes_update(
        self, model, dtype: torch.dtype
    ) -> dict[str, torch.dtype]: ...
    def adjust_max_memory(
        self, max_memory: dict[str, int | str]
    ) -> dict[str, int | str]: ...
    def check_quantized_param(self, *args, **kwargs) -> bool: ...
    def param_needs_quantization(
        self, model: PreTrainedModel, param_name: str, **kwargs
    ) -> bool: ...
    def create_quantized_param(self, *args, **kwargs):  # -> None:
        ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_tp_plan(self, config): ...
    def update_ep_plan(self, config): ...
    def preprocess_model(self, model: PreTrainedModel, **kwargs):  # -> None:
        ...
    def postprocess_model(self, model: PreTrainedModel, **kwargs):  # -> None:
        ...
    def remove_quantization_config(self, model):  # -> None:
        ...
    def dequantize(self, model): ...
    def get_accelerator_warm_up_factor(self):  # -> Literal[4]:
        ...
    def update_param_name(self, param_name: str) -> str: ...
    @staticmethod
    def get_modules_to_not_convert(
        model: PreTrainedModel,
        skip_modules: list[str] | None = ...,
        keep_in_fp32_modules: list[str] | None = ...,
        add_default_skips: bool = ...,
    ):  # -> list[str | Any] | list[Any]:
        ...
    @property
    def is_qat_trainable(self) -> bool: ...
    @property
    def is_compileable(self) -> bool: ...
    def get_state_dict_and_metadata(
        self, model, safe_serialization=...
    ):  # -> tuple[None, dict[Any, Any]]:
        ...
    def update_state_dict_with_metadata(self, state_dict, metadata): ...
    @abstractmethod
    def is_serializable(self, safe_serialization=...):  # -> None:
        ...
    @property
    @abstractmethod
    def is_trainable(self):  # -> None:
        ...

class SequentialLlama4TextExperts(ModuleList):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

MODULES_TO_PATCH_FOR_QUANTIZATION = ...
