import torch

from .base import HfQuantizer
from ..utils.quantization_config import CompressedTensorsConfig

logger = ...

class CompressedTensorsHfQuantizer(HfQuantizer):
    requires_calibration = ...
    required_packages = ...
    def __init__(
        self, quantization_config: CompressedTensorsConfig, **kwargs
    ) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def update_tp_plan(self, config): ...
    @property
    def is_trainable(self):  # -> Literal[True]:
        ...
    def is_qat_trainable(self) -> bool: ...
    def is_serializable(self, safe_serialization=...) -> bool: ...
