from .base import HfQuantizer
from ..modeling_utils import PreTrainedModel

logger = ...
CHECKPOINT_KEYS = ...

class QuarkHfQuantizer(HfQuantizer):
    requires_calibration = ...
    required_packages = ...
    requires_parameters_quantization = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def param_needs_quantization(
        self, model: PreTrainedModel, param_name: str, **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self, model, param, param_name, param_device, **kwargs
    ):  # -> None:
        ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[False]:
        ...
    @property
    def is_trainable(self):  # -> Literal[False]:
        ...
