import torch

from .base import HfQuantizer
from ..modeling_utils import PreTrainedModel

logger = ...

class EetqHfQuantizer(HfQuantizer):
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def param_needs_quantization(
        self, model: PreTrainedModel, param_name: str, **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        **kwargs,
    ):  # -> None:
        ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
    @property
    def is_trainable(self) -> bool: ...
