import torch

from .base import HfQuantizer
from ..modeling_utils import PreTrainedModel
from ..utils import is_torchao_available

logger = ...

def fuzzy_match_size(config_name: str) -> str | None: ...

if is_torchao_available():
    SUPPORTED_SAFE_SERIALIZATION_CONFIGS = ...
    TORCHAO_VERSION = ...

class TorchAoHfQuantizer(HfQuantizer):
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_dtype(self, dtype):  # -> dtype:
        ...
    def get_state_dict_and_metadata(
        self, model, safe_serialization: bool | None = ...
    ):  # -> tuple[dict[Any, Any], dict[Any, Any]] | tuple[None, dict[Any, Any]]:
        ...
    def adjust_target_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def adjust_max_memory(
        self, max_memory: dict[str, int | str]
    ) -> dict[str, int | str]: ...
    def update_unexpected_keys(
        self, model, unexpected_keys: list[str]
    ) -> list[str]: ...
    def param_needs_quantization(
        self, model: PreTrainedModel, param_name: str, **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        **kwargs,
    ):  # -> None:
        ...
    def is_serializable(self, safe_serialization=...) -> bool: ...
    def get_accelerator_warm_up_factor(self):  # -> int:
        ...
    @property
    def is_trainable(self) -> bool: ...
    @property
    def is_compileable(self) -> bool: ...
    def set_metadata(self, checkpoint_files: list[str]):  # -> None:
        ...
