import torch

from .base import HfQuantizer
from ..utils.quantization_config import QuantizationConfigMixin

logger = ...

class GptqHfQuantizer(HfQuantizer):
    requires_calibration = ...
    required_packages = ...
    optimum_quantizer = ...
    def __init__(
        self, quantization_config: QuantizationConfigMixin, **kwargs
    ) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def update_device_map(self, device_map):  # -> dict[str, device] | dict[str, Any]:
        ...
    @property
    def is_trainable(self) -> bool: ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
