import torch

from .base import HfQuantizer
from ..modeling_utils import PreTrainedModel

logger = ...

class Bnb8BitHfQuantizer(HfQuantizer):
    use_keep_in_fp32_modules = ...
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def adjust_max_memory(
        self, max_memory: dict[str, int | str]
    ) -> dict[str, int | str]: ...
    def update_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    def update_device_map(
        self, device_map
    ):  # -> dict[str, int] | dict[str, str] | dict[str, Any]:
        ...
    def adjust_target_dtype(self, target_dtype: torch.dtype) -> torch.dtype: ...
    def update_unexpected_keys(
        self, model, unexpected_keys: list[str]
    ) -> list[str]: ...
    def param_needs_quantization(
        self, model: PreTrainedModel, param_name: str, **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        **kwargs,
    ):  # -> None:
        ...
    def is_serializable(self, safe_serialization=...):  # -> bool:
        ...
    @property
    def is_trainable(self) -> bool: ...
