import torch

from .base import HfQuantizer
from ..modeling_utils import PreTrainedModel
from ..utils import is_hqq_available

if is_hqq_available():
    @property
    def weight(self):  # -> Tensor:
        ...

logger = ...

class HqqHfQuantizer(HfQuantizer):
    use_keep_in_fp32_modules = ...
    requires_parameters_quantization = ...
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def update_missing_keys(
        self, model: PreTrainedModel, missing_keys: list[str], prefix: str, **kwargs
    ) -> list[str]: ...
    def update_expected_keys(
        self, model: PreTrainedModel, expected_keys: list[str], loaded_keys: list[str]
    ) -> list[str]: ...
    def param_needs_quantization(
        self, model: PreTrainedModel, param_name: str, **kwargs
    ) -> bool: ...
    def create_quantized_param(
        self,
        model: PreTrainedModel,
        param_value: torch.Tensor,
        param_name: str,
        target_device: torch.device,
        **kwargs,
    ):  # -> None:
        ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
    @property
    def is_trainable(self) -> bool: ...
