import torch

from .base import HfQuantizer
from ..utils.quantization_config import QuantizationConfigMixin

logger = ...

class AutoRoundQuantizer(HfQuantizer):
    requires_calibration = ...
    required_packages = ...
    def __init__(
        self, quantization_config: QuantizationConfigMixin, **kwargs
    ) -> None: ...
    def validate_environment(self, *args, **kwargs):  # -> None:
        ...
    def update_dtype(self, dtype: torch.dtype) -> torch.dtype: ...
    @property
    def is_trainable(self) -> bool: ...
    def is_serializable(self, safe_serialization=...):  # -> Literal[True]:
        ...
