from .base import HfQuantizer

logger = ...

class AwqQuantizer(HfQuantizer):
    requires_calibration = ...
    required_packages = ...
    def __init__(self, quantization_config, **kwargs) -> None: ...
    def validate_environment(self, device_map, **kwargs):  # -> None:
        ...
    def update_dtype(self, dtype):  # -> dtype:
        ...
    def is_serializable(self, safe_serialization=...):  # -> bool:
        ...
    @property
    def is_trainable(self):  # -> bool:
        ...
