_HAS_GFILE_JOIN = ...

def make_tsv(metadata, save_path, metadata_header=...) -> None: ...
def make_sprite(label_img, save_path) -> None: ...
def get_embedding_info(metadata, label_img, subdir, global_step, tag): ...
def write_pbtxt(save_path, contents) -> None: ...
def make_mat(matlist, save_path) -> None: ...
