methods_OP = ...
methods_IO = ...
GETATTR_KIND = ...
CLASSTYPE_KIND = ...

class NodeBase:
    def __init__(
        self,
        debugName=...,
        inputs=...,
        scope=...,
        tensor_size=...,
        op_type=...,
        attributes=...,
    ) -> None: ...
    def __repr__(self) -> LiteralString: ...

class NodePy(NodeBase):
    def __init__(self, node_cpp, valid_methods) -> None: ...

class NodePyIO(NodePy):
    def __init__(self, node_cpp, input_or_output=...) -> None: ...

class NodePyOP(NodePy):
    def __init__(self, node_cpp) -> None: ...

class GraphPy:
    def __init__(self) -> None: ...
    def append(self, x) -> None: ...
    def printall(self) -> None: ...
    def find_common_root(self) -> None: ...
    def populate_namespace_from_OP_to_IO(self) -> None: ...
    def to_proto(self) -> list[Any]: ...

def parse(graph, trace, args=..., omit_useless_nodes=...) -> list[Any]: ...
def graph(model, args, verbose=..., use_strict_trace=...) -> tuple[Any, Any]: ...
