import torch

from ...image_processing_utils_fast import BaseImageProcessorFast
from ...utils import auto_docstring

"""Fast Image processor class for Perceiver."""

@auto_docstring
class PerceiverImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    def center_crop(
        self,
        image: torch.Tensor,
        crop_size: dict[str, int],
        size: dict[str, int],
        **kwargs,
    ) -> torch.Tensor: ...

__all__ = ["PerceiverImageProcessorFast"]
