from typing import Any
from dataclasses import dataclass

from torch import nn

import torch

from .configuration_xcodec import XcodecConfig
from ...modeling_utils import PreTrainedAudioTokenizerBase
from ...utils import ModelOutput, auto_docstring

"""Transformers Xcodec model."""

@dataclass
class XcodecOutput(ModelOutput):
    audio_codes: torch.LongTensor | None = ...
    audio_values: torch.FloatTensor | None = ...

@dataclass
class XcodecEncoderOutput(ModelOutput):
    audio_codes: torch.LongTensor | None = ...

@dataclass
class XcodecDecoderOutput(ModelOutput):
    audio_values: torch.FloatTensor | None = ...

class ResidualUnit(nn.Module):
    def __init__(
        self, config: XcodecConfig, in_channels: int, out_channels: int, dilation: int
    ) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class SemanticEncoderBlock(nn.Module):
    def __init__(
        self, config: XcodecConfig, in_channels: int, out_channels: int, stride: int
    ) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class SemanticEncoder(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class SemanticDecoderBlock(nn.Module):
    def __init__(
        self, config: XcodecConfig, in_channels: int, out_channels: int, stride: int
    ) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class SemanticDecoder(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class XcodecEuclideanCodebook(nn.Module):
    def __init__(self, config) -> None: ...
    def quantize(self, hidden_states): ...
    def encode(self, hidden_states): ...
    def decode(self, embed_ind):  # -> Tensor:
        ...

class XcodecVectorQuantization(nn.Module):
    def __init__(self, config: XcodecConfig) -> None: ...
    def encode(self, hidden_states): ...
    def decode(self, embed_ind):  # -> Tensor:
        ...

class XcodecResidualVectorQuantization(nn.Module):
    def __init__(self, config: XcodecConfig) -> None: ...
    def get_bandwidth_per_quantizer(self):  # -> float:
        ...
    def get_num_quantizers_for_bandwidth(self, bandwidth=...) -> int: ...
    def encode(self, embeddings: torch.Tensor, bandwidth=...) -> torch.Tensor: ...
    def decode(self, codes: torch.Tensor) -> torch.Tensor: ...

@auto_docstring
class XcodecPreTrainedModel(PreTrainedAudioTokenizerBase):
    config_class = XcodecConfig
    base_model_prefix = ...
    main_input_name = ...
    def apply_weight_norm(self):  # -> None:
        ...
    def remove_weight_norm(self):  # -> None:
        ...

@auto_docstring(custom_intro="""The Xcodec neural audio codec model.""")
class XcodecModel(XcodecPreTrainedModel):
    def __init__(self, config) -> None: ...
    @auto_docstring
    def encode(
        self,
        input_values: torch.Tensor,
        bandwidth: float | None = ...,
        return_dict: bool | None = ...,
    ) -> torch.Tensor | XcodecEncoderOutput: ...
    @auto_docstring
    def decode(
        self, audio_codes: torch.Tensor, return_dict: bool | None = ...
    ) -> torch.Tensor | XcodecDecoderOutput: ...
    @auto_docstring
    def forward(
        self,
        input_values: torch.Tensor,
        audio_codes: torch.Tensor | None = ...,
        bandwidth: float | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor] | XcodecOutput: ...

__all__ = ["XcodecModel", "XcodecPreTrainedModel"]
