from collections.abc import Generator
from contextlib import contextmanager as contextmanager
from functools import lru_cache as _lru_cache
from typing import Any as Any

from torch.backends import (
    ContextProp as ContextProp,
    PropModule as PropModule,
    __allow_nonbracketed_mutation as __allow_nonbracketed_mutation,
)

@_lru_cache
def is_available() -> bool: ...
def get_opt_einsum() -> Any: ...
def set_flags(
    _enabled=..., _strategy=...
) -> tuple[ContextProp | bool, ContextProp | str | None]: ...
@contextmanager
def flags(enabled=..., strategy=...) -> Generator[None, Any, None]: ...

class OptEinsumModule(PropModule):
    def __init__(self, m, name) -> None: ...

    enabled = ...
    strategy = ...
    if is_available():
        strategy = ...

enabled = ...
strategy = ...
