from torchvision.transforms.v2 import functional as F

import torch

from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import SizeDict
from ...utils import auto_docstring

"""Fast Image processor class for Vilt."""
MAX_LONGER_EDGE = ...
MAX_SHORTER_EDGE = ...

class ViltFastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    size_divisor: int | None
    rescale_factor: float | None

@auto_docstring
class ViltImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    size_divisor = ...
    do_pad = ...
    default_to_square = ...
    model_input_names = ...
    valid_kwargs = ViltFastImageProcessorKwargs
    def resize(
        self,
        images: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode | None = ...,
        size_divisor: int | None = ...,
    ) -> torch.Tensor: ...

__all__ = ["ViltImageProcessorFast"]
