from collections.abc import Generator
from enum import Enum
from typing import Any

from PIL import Image

import numpy as np

class _WebPLib:
    MODE_RGB: int
    VP8_STATUS_OK: int
    def WebPInitDecoderConfig(self, config: Any) -> int: ...
    def WebPDecode(self, data_bytes: Any, data_size: int, config: Any) -> int: ...
    def WebPFreeDecBuffer(self, output: Any) -> None: ...

class _WebPFFI:
    def from_buffer(self, buf: bytes) -> Any: ...
    def buffer(self, ptr: Any, size: Any) -> bytes: ...

lib: _WebPLib
ffi: _WebPFFI

class WebPPreset(Enum):
    DEFAULT = ...
    PICTURE = ...
    PHOTO = ...
    DRAWING = ...
    ICON = ...
    TEXT = ...

class WebPColorMode(Enum):
    RGB = ...
    RGBA = ...
    BGR = ...
    BGRA = ...
    ARGB = ...
    RGBA_4444 = ...
    RGB_565 = ...
    rgbA = ...
    bgrA = ...
    Argb = ...
    rgbA_4444 = ...
    YUV = ...
    YUVA = ...
    LAST = ...

class WebPError(Exception): ...

class WebPConfig:
    DEFAULT_QUALITY: float = ...
    def __init__(self, ptr: Any) -> None: ...
    @property
    def lossless(self) -> bool: ...
    @lossless.setter
    def lossless(self, lossless: bool) -> None: ...
    @property
    def quality(self) -> float: ...
    @quality.setter
    def quality(self, quality: float) -> None: ...
    @property
    def method(self) -> int: ...
    @method.setter
    def method(self, method: int) -> None: ...
    @property
    def target_size(self) -> int: ...
    @target_size.setter
    def target_size(self, target_size: int) -> None: ...
    @property
    def passes(self) -> int: ...
    @passes.setter
    def passes(self, passes: int) -> None: ...
    def validate(self) -> bool: ...
    @staticmethod
    def new(
        preset: WebPPreset = ...,
        quality: float | None = ...,
        lossless: bool = ...,
        lossless_preset: int | None = ...,
        method: int | None = ...,
        *,
        target_size: int | None = ...,
        passes: int | None = ...,
    ) -> WebPConfig: ...

class WebPData:
    bytes: Any
    size: int
    def __init__(self, ptr: Any = ..., data_ref: Any = ...) -> None: ...
    def buffer(self) -> bytes: ...
    def decode(
        self, color_mode: WebPColorMode = ...
    ) -> np.ndarray[Any, np.dtype[np.uint8]]: ...
    @staticmethod
    def from_buffer(buf: bytes) -> WebPData: ...

class _WebPData:
    def __init__(self) -> None: ...
    def done(self, free_func: Any = ...) -> WebPData: ...

class WebPMemoryWriter:
    def __init__(self, ptr: Any) -> None: ...
    def __del__(self) -> None: ...
    def to_webp_data(self) -> WebPData: ...
    @staticmethod
    def new() -> WebPMemoryWriter: ...

class WebPPicture:
    def __init__(self, ptr: Any) -> None: ...
    def __del__(self) -> None: ...
    def encode(self, config: WebPConfig | None = ...) -> WebPData: ...
    def save(self, file_path: str, config: WebPConfig | None = ...) -> None: ...
    @staticmethod
    def new(width: int, height: int) -> WebPPicture: ...
    @staticmethod
    def from_numpy(
        arr: np.ndarray[Any, np.dtype[np.uint8]], *, pilmode: str | None = ...
    ) -> WebPPicture: ...
    @staticmethod
    def from_pil(img: Image.Image) -> WebPPicture: ...

class WebPDecoderConfig:
    def __init__(self, ptr: Any = ...) -> None: ...
    @property
    def input(self) -> Any: ...
    @property
    def output(self) -> Any: ...
    @property
    def options(self) -> Any: ...
    def read_features(self, webp_data: WebPData) -> None: ...
    @staticmethod
    def new() -> WebPDecoderConfig: ...

class WebPAnimEncoderOptions:
    def __init__(self, ptr: Any) -> None: ...
    @property
    def loop_count(self) -> int: ...
    @loop_count.setter
    def loop_count(self, loop_count: int) -> None: ...
    @property
    def minimize_size(self) -> bool: ...
    @minimize_size.setter
    def minimize_size(self, minimize_size: bool) -> None: ...
    @property
    def allow_mixed(self) -> bool: ...
    @allow_mixed.setter
    def allow_mixed(self, allow_mixed: bool) -> None: ...
    @staticmethod
    def new(
        minimize_size: bool = ..., allow_mixed: bool = ...
    ) -> WebPAnimEncoderOptions: ...

class WebPAnimEncoder:
    def __init__(self, ptr: Any, enc_opts: WebPAnimEncoderOptions) -> None: ...
    def __del__(self) -> None: ...
    def encode_frame(
        self, frame: WebPPicture, timestamp_ms: int, config: WebPConfig | None = ...
    ) -> None: ...
    def assemble(self, end_timestamp_ms: int) -> WebPData: ...
    @staticmethod
    def new(
        width: int, height: int, enc_opts: WebPAnimEncoderOptions | None = ...
    ) -> WebPAnimEncoder: ...

class WebPAnimDecoderOptions:
    def __init__(self, ptr: Any) -> None: ...
    @property
    def color_mode(self) -> WebPColorMode: ...
    @color_mode.setter
    def color_mode(self, color_mode: WebPColorMode) -> None: ...
    @property
    def use_threads(self) -> bool: ...
    @use_threads.setter
    def use_threads(self, use_threads: bool) -> None: ...
    @staticmethod
    def new(
        use_threads: bool = ..., color_mode: WebPColorMode = ...
    ) -> WebPAnimDecoderOptions: ...

class WebPAnimInfo:
    def __init__(self, ptr: Any) -> None: ...
    @property
    def frame_count(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def loop_count(self) -> int: ...
    @staticmethod
    def new() -> WebPAnimInfo: ...

class WebPAnimDecoder:
    def __init__(
        self, ptr: Any, dec_opts: WebPAnimDecoderOptions, anim_info: WebPAnimInfo
    ) -> None: ...
    def __del__(self) -> None: ...
    def has_more_frames(self) -> bool: ...
    def reset(self) -> None: ...
    def decode_frame(self) -> tuple[np.ndarray[Any, np.dtype[np.uint8]], int]: ...
    def frames(
        self,
    ) -> Generator[tuple[np.ndarray[Any, np.dtype[np.uint8]], int]]: ...
    @staticmethod
    def new(
        webp_data: WebPData, dec_opts: WebPAnimDecoderOptions | None = ...
    ) -> WebPAnimDecoder: ...

def imwrite(
    file_path: str,
    arr: np.ndarray[Any, np.dtype[np.uint8]],
    pilmode: str | None = ...,
    **kwargs: Any,
) -> None: ...
def imread(
    file_path: str, pilmode: str = ...
) -> np.ndarray[Any, np.dtype[np.uint8]]: ...
def mimwrite(
    file_path: str,
    arrs: list[np.ndarray[Any, np.dtype[np.uint8]]],
    fps: float = ...,
    loop_count: int | None = ...,
    pilmode: str | None = ...,
    **kwargs: Any,
) -> None: ...
def mimread(
    file_path: str,
    fps: float | None = ...,
    use_threads: bool = ...,
    pilmode: str = ...,
) -> list[np.ndarray[Any, np.dtype[np.uint8]]]: ...
def save_image(img: Image.Image, file_path: str, **kwargs: Any) -> None: ...
def load_image(file_path: str, mode: str = ...) -> Image.Image: ...
def save_images(imgs: list[Image.Image], file_path: str, **kwargs: Any) -> None: ...
def load_images(
    file_path: str, mode: str = ..., **kwargs: Any
) -> list[Image.Image]: ...
