from logging import Logger

class AsyncOAuthStateStore:
    @property
    def logger(self) -> Logger: ...
    async def async_issue(self, *args, **kwargs) -> str: ...
    async def async_consume(self, state: str) -> bool: ...
