import enum

__all__ = (
    "DEBUG_AUTOCLOSE",
    "LIBRARY_AVAILABLE",
    "AutoCastable",
    "AutoCloseable",
    "ObjectTracker",
    "_debug_close",
    "_warn_close",
)
logger = ...
LIBRARY_AVAILABLE = ...
ObjectTracker = ...

class _STATE(enum.Enum):
    INVALID = ...
    AUTO = ...
    EXPLICIT = ...
    BYPARENT = ...

class _FinalizerInfo:
    __slots__ = ...
    def __init__(self, close_func, args, kwargs, tracked) -> None: ...

class _FinalizerOwner:
    __slots__ = ...
    def __init__(self, raw, parent, wref, type, repr) -> None: ...

class AutoCastable: ...

class AutoCloseable(AutoCastable):
    def __init__(
        self, close_func, *args, obj=..., needs_free=..., tracked=..., **kwargs
    ) -> None: ...
    def close(self, _by_parent=...) -> bool: ...
