import enum

from pypdfium2.version import PDFIUM_INFO

class _fallback_dict(dict):
    def get(self, key, default_prefix=...): ...

RotationToConst = ...
RotationToDegrees = ...
BitmapTypeToNChannels = ...
BitmapTypeToStr = ...
BitmapTypeToStrReverse = ...
BitmapStrToConst = ...
BitmapStrReverseToConst = ...
FormTypeToStr = ...
ColorspaceToStr = ...
ViewmodeToStr = ...
ObjectTypeToStr = ...
ObjectTypeToConst = ...
PageModeToStr = ...
ErrorToStr = ...
if "XFA" in PDFIUM_INFO.flags:
    XFAErrorToStr = ...
UnsupportedInfoToStr = ...
CharsetToStr = ...

class PdfFontPitchFamilyFlags(enum.Flag):
    FIXEDPITCH = ...
    ROMAN = ...
    SCRIPT = ...
