from typing import Any, Literal

def color_tohex(color, rev_byteorder) -> Literal[0]: ...
def set_callback(struct, fname, callback) -> None: ...
def set_callbacks(struct, **kwargs) -> None: ...
def is_stream(buf, spec=...) -> bool: ...
def get_buffer(ptr, size): ...

class _buffer_reader:
    def __init__(self, py_buffer) -> None: ...
    def __call__(self, _, position, p_buf_first, size) -> Literal[1]: ...

class _buffer_writer:
    def __init__(self, py_buffer) -> None: ...
    def __call__(self, _, p_data_first, size) -> Literal[1]: ...

def get_bufreader(buffer) -> tuple[FPDF_FILEACCESS, tuple[Any]]: ...
def get_bufwriter(buffer) -> FPDF_FILEWRITE: ...
def pages_c_array(
    pages,
) -> tuple[None, Literal[0]] | tuple[Array[_Pointer[struct_fpdf_page_t__]], int]: ...

FPDF_WCHAR_size = ...
