from torch import Tensor
from typing import Any

def sparse_semi_structured_from_dense_cutlass(dense) -> tuple[Tensor | Any, Any]: ...
def sparse_semi_structured_to_dense_cutlass(sparse, meta_reordered) -> Tensor: ...
