from typing import Any
from collections import OrderedDict

from torch import Tensor, nn

from .integrations.hub_kernels import use_kernel_forward_from_hub

logger = ...

@use_kernel_forward_from_hub("GeluTanh")
class GELUTanh(nn.Module):
    def __init__(self, use_gelu_tanh_python: bool = ...) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

@use_kernel_forward_from_hub("NewGELU")
class NewGELUActivation(nn.Module):
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

@use_kernel_forward_from_hub("GeLU")
class GELUActivation(nn.Module):
    def __init__(self, use_gelu_python: bool = ...) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

@use_kernel_forward_from_hub("SiLU")
class SiLUActivation(nn.Module):
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

@use_kernel_forward_from_hub("FastGELU")
class FastGELUActivation(nn.Module):
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

@use_kernel_forward_from_hub("QuickGELU")
class QuickGELUActivation(nn.Module):
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class ClippedGELUActivation(nn.Module):
    def __init__(self, min: float, max: float) -> None: ...
    def forward(self, x: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class AccurateGELUActivation(nn.Module):
    def __init__(self) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class MishActivation(nn.Module):
    def __init__(self) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class LinearActivation(nn.Module):
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

class LaplaceActivation(nn.Module):
    def forward(self, input, mu=..., sigma=...):  # -> Tensor:
        ...

class ReLUSquaredActivation(nn.Module):
    def forward(self, input):  # -> Tensor:
        ...

class ClassInstantier(OrderedDict):
    def __getitem__(self, key): ...

class XIELUActivation(nn.Module):
    def __init__(
        self,
        alpha_p_init=...,
        alpha_n_init=...,
        beta=...,
        eps=...,
        dtype=...,
        with_vector_loads=...,
    ) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Tensor: ...

ACT2CLS = ...
ACT2FN = ...

def get_activation(activation_string): ...

gelu_python = ...
gelu_new = ...
gelu = ...
gelu_fast = ...
quick_gelu = ...
silu = ...
mish = ...
linear_act = ...
