from abc import ABC, abstractmethod
from collections.abc import Iterable
from typing import Any

import torch

from .configuration_utils import PretrainedConfig

_is_torch_greater_or_equal_than_2_7 = ...
logger = ...

class CacheLayerMixin(ABC):
    is_compileable = ...
    def __init__(self) -> None: ...
    def __repr__(self):  # -> str:
        ...
    @abstractmethod
    def lazy_initialization(self, key_states: torch.Tensor):  # -> None:
        ...
    @abstractmethod
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    @abstractmethod
    def get_mask_sizes(self, cache_position: torch.Tensor) -> tuple[int, int]: ...
    @abstractmethod
    def get_seq_length(self) -> int: ...
    @abstractmethod
    def get_max_cache_shape(self) -> int: ...
    def offload(self):  # -> None:
        ...
    def prefetch(self):  # -> None:
        ...
    def reset(self) -> None: ...
    def reorder_cache(self, beam_idx: torch.LongTensor) -> None: ...

class DynamicLayer(CacheLayerMixin):
    is_sliding = ...
    def lazy_initialization(self, key_states: torch.Tensor):  # -> None:
        ...
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def get_mask_sizes(self, cache_position: torch.Tensor) -> tuple[int, int]: ...
    def get_seq_length(self) -> int: ...
    def get_max_cache_shape(self) -> int: ...
    def crop(self, max_length: int) -> None: ...
    def batch_repeat_interleave(self, repeats: int) -> None: ...
    def batch_select_indices(self, indices: torch.Tensor) -> None: ...

class DynamicSlidingWindowLayer(DynamicLayer):
    is_sliding = ...
    def __init__(self, sliding_window: int) -> None: ...
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def get_mask_sizes(self, cache_position: torch.Tensor) -> tuple[int, int]: ...
    def get_seq_length(self) -> int: ...
    def get_max_cache_shape(self) -> int: ...
    def crop(self, max_length: int) -> None: ...

class StaticLayer(CacheLayerMixin):
    is_compileable = ...
    is_sliding = ...
    def __init__(self, max_cache_len: int) -> None: ...
    def lazy_initialization(self, key_states: torch.Tensor):  # -> None:
        ...
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def get_mask_sizes(self, cache_position: torch.Tensor) -> tuple[int, int]: ...
    def get_seq_length(self) -> int: ...
    def get_max_cache_shape(self) -> int: ...

class StaticSlidingWindowLayer(StaticLayer):
    is_sliding = ...
    def __init__(self, max_cache_len: int, sliding_window: int) -> None: ...
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def get_mask_sizes(self, cache_position: torch.Tensor) -> tuple[int, int]: ...
    def get_seq_length(self) -> int: ...

class QuantizedLayer(DynamicLayer):
    def __init__(
        self,
        nbits: int = ...,
        axis_key: int = ...,
        axis_value: int = ...,
        q_group_size: int = ...,
        residual_length: int = ...,
    ) -> None: ...
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def get_seq_length(self) -> int: ...

class QuantoQuantizedLayer(QuantizedLayer):
    def __init__(
        self,
        nbits: int = ...,
        axis_key: int = ...,
        axis_value: int = ...,
        q_group_size: int = ...,
        residual_length: int = ...,
    ) -> None: ...

class HQQQuantizedLayer(QuantizedLayer):
    def __init__(
        self,
        nbits: int = ...,
        axis_key: int = ...,
        axis_value: int = ...,
        q_group_size: int = ...,
        residual_length: int = ...,
    ) -> None: ...

class Cache:
    def __init__(
        self,
        layers: list[CacheLayerMixin] | None = ...,
        layer_class_to_replicate: type[CacheLayerMixin] | None = ...,
        offloading: bool = ...,
        offload_only_non_sliding: bool = ...,
    ) -> None: ...
    def __repr__(self):  # -> str:
        ...
    def prefetch(self, layer_idx: int, only_non_sliding: bool = ...):  # -> None:
        ...
    def offload(self, layer_idx: int, only_non_sliding: bool = ...):  # -> None:
        ...
    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        layer_idx: int,
        cache_kwargs: dict[str, Any] | None = ...,
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def early_initialization(
        self,
        batch_size: int,
        num_heads: int,
        head_dim: int,
        dtype: torch.dtype,
        device: torch.device,
    ):  # -> None:
        ...
    def get_seq_length(self, layer_idx: int = ...) -> int: ...
    def get_mask_sizes(
        self, cache_position: torch.Tensor, layer_idx: int
    ) -> tuple[int, int]: ...
    def get_max_cache_shape(self, layer_idx: int = ...) -> int: ...
    def reset(self):  # -> None:
        ...
    def reorder_cache(self, beam_idx: torch.LongTensor):  # -> None:
        ...
    def crop(self, max_length: int):  # -> None:
        ...
    def batch_repeat_interleave(self, repeats: int):  # -> None:
        ...
    def batch_select_indices(self, indices: torch.Tensor):  # -> None:
        ...
    @property
    def max_batch_size(self) -> int: ...
    @property
    def max_cache_len(self) -> int: ...
    @property
    def is_compileable(self) -> bool: ...
    @property
    def is_initialized(self) -> bool: ...
    @property
    def is_sliding(self) -> list[bool]: ...
    def __getitem__(self, layer_idx: int) -> tuple[torch.Tensor, torch.Tensor]: ...
    def __iter__(self):  # -> Generator[tuple[Tensor | None, Tensor | None], Any, None]:
        ...
    def __len__(self):  # -> int:
        ...

class DynamicCache(Cache):
    def __init__(
        self,
        ddp_cache_data: Iterable[tuple[torch.Tensor, torch.Tensor]] | None = ...,
        config: PretrainedConfig | None = ...,
        offloading: bool = ...,
        offload_only_non_sliding: bool = ...,
    ) -> None: ...
    def to_legacy_cache(self) -> tuple[tuple[torch.Tensor, torch.Tensor]]: ...
    @classmethod
    def from_legacy_cache(
        cls, past_key_values: tuple[tuple[torch.Tensor, torch.Tensor]]
    ) -> DynamicCache: ...

class StaticCache(Cache):
    def __init__(
        self,
        config: PretrainedConfig,
        max_cache_len: int,
        offloading: bool = ...,
        offload_only_non_sliding: bool = ...,
        **kwargs,
    ) -> None: ...

class QuantizedCache(Cache):
    def __init__(
        self,
        backend: str,
        config: PretrainedConfig,
        nbits: int = ...,
        axis_key: int = ...,
        axis_value: int = ...,
        q_group_size: int = ...,
        residual_length: int = ...,
    ) -> None: ...

class EncoderDecoderCache(Cache):
    def __init__(self, *caches) -> None: ...
    def __iter__(
        self,
    ):  # -> Generator[tuple[Tensor | None, Tensor | None, Tensor | None, Tensor | None], Any, None]:
        ...
    def __getitem__(
        self, layer_idx: int
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]: ...
    def __len__(self):  # -> int:
        ...
    def to_legacy_cache(self) -> tuple[tuple[torch.Tensor]]: ...
    @classmethod
    def from_legacy_cache(
        cls, past_key_values: Iterable[tuple[torch.FloatTensor, ...]] | None
    ) -> EncoderDecoderCache: ...
    def get_seq_length(self, layer_idx: int = ...) -> int: ...
    def reset(self):  # -> None:
        ...
    def reorder_cache(self, beam_idx: torch.LongTensor):  # -> None:
        ...
    def check_dynamic_cache(self, method: str):  # -> None:
        ...
    def crop(self, maximum_length: int):  # -> None:
        ...
    def batch_split(
        self, full_batch_size: int, split_size: int
    ) -> list[EncoderDecoderCache]: ...
    def batch_repeat_interleave(self, repeats: int):  # -> None:
        ...
    def batch_select_indices(self, indices: torch.Tensor):  # -> None:
        ...
    def get_max_cache_shape(self) -> int: ...
    def get_mask_sizes(
        self, cache_position: torch.Tensor, layer_idx: int
    ) -> tuple[int, int]: ...
    @property
    def is_sliding(self):  # -> list[bool]:
        ...
    @property
    def is_compileable(self) -> bool: ...

class SlidingWindowLayer(StaticSlidingWindowLayer):
    def __init__(self, max_cache_len: int, sliding_window: int) -> None: ...

class ChunkedSlidingLayer(StaticSlidingWindowLayer):
    def __init__(self, max_cache_len: int, sliding_window: int) -> None: ...

class OffloadedCache(DynamicCache):
    def __init__(self) -> None: ...

class OffloadedStaticCache(StaticCache):
    def __init__(
        self, config: PretrainedConfig, max_cache_len: int, *args, **kwargs
    ) -> None: ...

class SlidingWindowCache(StaticCache):
    def __init__(
        self, config: PretrainedConfig, max_cache_len: int, *args, **kwargs
    ) -> None: ...

class HybridCache(StaticCache):
    def __init__(
        self, config: PretrainedConfig, max_cache_len: int, *args, **kwargs
    ) -> None: ...

class HybridChunkedCache(StaticCache):
    def __init__(
        self, config: PretrainedConfig, max_cache_len: int, *args, **kwargs
    ) -> None: ...

class OffloadedHybridCache(StaticCache):
    def __init__(
        self, config: PretrainedConfig, max_cache_len: int, *args, **kwargs
    ) -> None: ...

class QuantoQuantizedCache(QuantizedCache):
    def __init__(
        self,
        config: PretrainedConfig,
        nbits: int = ...,
        axis_key: int = ...,
        axis_value: int = ...,
        q_group_size: int = ...,
        residual_length: int = ...,
    ) -> None: ...

class HQQQuantizedCache(QuantizedCache):
    def __init__(
        self,
        config: PretrainedConfig,
        nbits: int = ...,
        axis_key: int = ...,
        axis_value: int = ...,
        q_group_size: int = ...,
        residual_length: int = ...,
    ) -> None: ...

class SinkCache(Cache):
    def __init__(self, **kwargs) -> None: ...
