from .configuration_utils import PretrainedConfig

logger = ...

def dynamic_rope_update(rope_forward):  # -> _Wrapped[..., Any, ..., Any]:
    ...

ROPE_INIT_FUNCTIONS = ...
ROPE_VALIDATION_FUNCTIONS = ...

def rope_config_validation(
    config: PretrainedConfig, ignore_keys: set | None = ...
):  # -> None:
    ...
