from collections.abc import Callable
from typing import Any, Generic, TypeVar

import collections

from torch._C._distributed_rpc import PyRRef

__all__ = [
    "AllGatherStates",
    "RRef",
    "get_worker_info",
    "method_factory",
    "new_method",
    "remote",
    "rpc_async",
    "rpc_sync",
    "shutdown",
]
logger = ...
_ignore_rref_leak = ...
_default_pickler = ...

class AllGatherStates:
    def __init__(self) -> None: ...

_ALL_WORKER_NAMES: set[Any] = ...
_all_gather_dict_lock = ...
_all_gather_sequence_id: dict[str, int] = ...
_all_gather_sequence_id_to_states: collections.defaultdict = ...
_thread_local_var = ...

def shutdown(graceful=..., timeout=...) -> None: ...
def get_worker_info(worker_name=...) -> WorkerInfo: ...

T = TypeVar("T")
type GenericWithOneTypeVar[T] = Generic[T]

class RRef(PyRRef[T], Generic[T]): ...

def method_factory(method_name, docstring) -> Callable[..., Any]: ...
def remote(to, func, args=..., kwargs=..., timeout=...): ...
def rpc_sync(to, func, args=..., kwargs=..., timeout: float = ...) -> Any: ...
def rpc_async(to, func, args=..., kwargs=..., timeout=...) -> Future[Any]: ...
