from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    BatchFeature,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for LayoutLMv3."""
logger = ...

class LayoutLMv3FastImageProcessorKwargs(DefaultFastImageProcessorKwargs):
    apply_ocr: bool | None
    ocr_lang: str | None
    tesseract_config: str | None

@auto_docstring
class LayoutLMv3ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    apply_ocr = ...
    ocr_lang = ...
    tesseract_config = ...
    valid_kwargs = LayoutLMv3FastImageProcessorKwargs
    def __init__(
        self, **kwargs: Unpack[LayoutLMv3FastImageProcessorKwargs]
    ) -> None: ...
    @auto_docstring
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[LayoutLMv3FastImageProcessorKwargs]
    ) -> BatchFeature: ...

__all__ = ["LayoutLMv3ImageProcessorFast"]
