from .interval_calculator import RetryIntervalCalculator
from .jitter import Jitter

class FixedValueRetryIntervalCalculator(RetryIntervalCalculator):
    fixed_interval: float
    def __init__(self, fixed_internal: float = ...) -> None: ...
    def calculate_sleep_duration(self, current_attempt: int) -> float: ...

class BackoffRetryIntervalCalculator(RetryIntervalCalculator):
    backoff_factor: float
    jitter: Jitter
    def __init__(
        self, backoff_factor: float = ..., jitter: Jitter | None = ...
    ) -> None: ...
    def calculate_sleep_duration(self, current_attempt: int) -> float: ...
