import torch

from .modeling_owlv2 import Owlv2ObjectDetectionOutput
from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput, SizeDict
from ...processing_utils import Unpack
from ...utils import TensorType, auto_docstring

class Owlv2FastImageProcessorKwargs(DefaultFastImageProcessorKwargs): ...

@auto_docstring
class Owlv2ImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    model_input_names = ...
    rescale_factor = ...
    do_pad = ...
    valid_kwargs = Owlv2FastImageProcessorKwargs
    def post_process(self, outputs, target_sizes):  # -> list[dict[str, Tensor | str]]:
        ...
    def post_process_object_detection(
        self,
        outputs: Owlv2ObjectDetectionOutput,
        threshold: float = ...,
        target_sizes: TensorType | list[tuple] | None = ...,
    ):  # -> list[Any]:
        ...
    def post_process_image_guided_detection(
        self, outputs, threshold=..., nms_threshold=..., target_sizes=...
    ):  # -> list[Any]:
        ...
    def __init__(self, **kwargs: Unpack[Owlv2FastImageProcessorKwargs]) -> None: ...
    @auto_docstring
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[Owlv2FastImageProcessorKwargs]
    ):  # -> BatchFeature:
        ...
    def pad(
        self,
        images: list[torch.Tensor],
        disable_grouping: bool | None,
        constant_value: float = ...,
        **kwargs,
    ) -> list[torch.Tensor]: ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        anti_aliasing: bool = ...,
        anti_aliasing_sigma=...,
        **kwargs,
    ) -> torch.Tensor: ...

__all__ = ["Owlv2ImageProcessorFast"]
