import torch

from ...image_processing_utils import BatchFeature
from ...image_processing_utils_fast import (
    BaseImageProcessorFast,
    DefaultFastImageProcessorKwargs,
)
from ...image_utils import ImageInput
from ...processing_utils import Unpack
from ...utils import auto_docstring

"""Fast Image processor class for LLaVa."""

class LlavaFastImageProcessorKwargs(DefaultFastImageProcessorKwargs): ...

@auto_docstring
class LlavaImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_pad = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    valid_kwargs = LlavaFastImageProcessorKwargs
    def __init__(self, **kwargs: Unpack[LlavaFastImageProcessorKwargs]) -> None: ...
    @auto_docstring
    def preprocess(
        self, images: ImageInput, **kwargs: Unpack[LlavaFastImageProcessorKwargs]
    ) -> BatchFeature: ...
    def pad_to_square(
        self,
        images: torch.Tensor,
        background_color: int | tuple[int, int, int] = ...,
    ) -> torch.Tensor: ...

__all__ = ["LlavaImageProcessorFast"]
