from torchvision.transforms.v2 import functional as F

import torch

from ...image_processing_utils_fast import BaseImageProcessorFast, SizeDict
from ...utils import auto_docstring

"""Fast Image processor class for LeViT."""

@auto_docstring
class LevitImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    default_to_square = ...
    crop_size = ...
    do_resize = ...
    do_center_crop = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    def resize(
        self,
        image: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode | None = ...,
        **kwargs,
    ) -> torch.Tensor: ...

__all__ = ["LevitImageProcessorFast"]
