from dataclasses import dataclass
from typing import Any

from torch import nn

import torch

from .configuration_dpt import DPTConfig
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import (
    BaseModelOutput,
    DepthEstimatorOutput,
    SemanticSegmenterOutput,
)
from ...modeling_utils import PreTrainedModel
from ...utils import ModelOutput, auto_docstring
from ...utils.generic import can_return_tuple, check_model_inputs

"""PyTorch DPT (Dense Prediction Transformers) model.

This implementation is heavily inspired by OpenMMLab's implementation, found here:
https://github.com/open-mmlab/mmsegmentation/blob/master/mmseg/models/decode_heads/dpt_head.py.

"""
logger = ...

@dataclass
@auto_docstring(custom_intro=...)
class BaseModelOutputWithIntermediateActivations(ModelOutput):
    last_hidden_states: torch.FloatTensor | None = ...
    intermediate_activations: tuple[torch.FloatTensor, ...] | None = ...

@dataclass
@auto_docstring(custom_intro=...)
class BaseModelOutputWithPoolingAndIntermediateActivations(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    pooler_output: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor, ...] | None = ...
    attentions: tuple[torch.FloatTensor, ...] | None = ...
    intermediate_activations: tuple[torch.FloatTensor, ...] | None = ...

class DPTViTHybridEmbeddings(nn.Module):
    def __init__(
        self, config: DPTConfig, feature_size: tuple[int, int] | None = ...
    ) -> None: ...
    def forward(
        self, pixel_values: torch.Tensor, interpolate_pos_encoding: bool = ...
    ) -> BaseModelOutputWithIntermediateActivations: ...
    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> BaseModelOutputWithIntermediateActivations: ...

class DPTViTEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: torch.Tensor
    ) -> BaseModelOutputWithIntermediateActivations: ...
    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> BaseModelOutputWithIntermediateActivations: ...

class DPTViTPatchEmbeddings(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, pixel_values: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class DPTSelfAttention(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> tuple[torch.Tensor, torch.Tensor]: ...

class DPTViTSelfOutput(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTViTAttention(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def prune_heads(self, heads: set[int]):  # -> None:
        ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTViTIntermediate(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTViTOutput(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTViTLayer(GradientCheckpointingLayer):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTViTEncoder(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        head_mask: torch.Tensor | None = ...,
        output_hidden_states: bool = ...,
    ) -> BaseModelOutput: ...
    def __call__(self, *args: Any, **kwargs: Any) -> BaseModelOutput: ...

class DPTReassembleStage(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self, hidden_states: list[torch.Tensor], patch_height=..., patch_width=...
    ) -> list[torch.Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> list[torch.Tensor]: ...

class DPTReassembleLayer(nn.Module):
    def __init__(self, config: DPTConfig, channels: int, factor: int) -> None: ...
    def forward(self, hidden_state):  # -> Any:
        ...

class DPTFeatureFusionStage(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states):  # -> list[Any]:
        ...

class DPTPreActResidualLayer(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_state: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTFeatureFusionLayer(nn.Module):
    def __init__(self, config: DPTConfig, align_corners: bool = ...) -> None: ...
    def forward(
        self, hidden_state: torch.Tensor, residual: torch.Tensor | None = ...
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

@auto_docstring
class DPTPreTrainedModel(PreTrainedModel):
    config: DPTConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...
    _can_record_outputs = ...

@auto_docstring
class DPTModel(DPTPreTrainedModel):
    def __init__(self, config: DPTConfig, add_pooling_layer: bool = ...) -> None: ...
    def get_input_embeddings(
        self,
    ):  # -> DPTViTHybridEmbeddings | DPTViTEmbeddings | Tensor | Module | DPTViTPatchEmbeddings:
        ...
    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        head_mask: torch.FloatTensor | None = ...,
        output_hidden_states: bool | None = ...,
        **kwargs,
    ) -> BaseModelOutputWithPoolingAndIntermediateActivations: ...

class DPTViTPooler(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTNeck(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(
        self,
        hidden_states: list[torch.Tensor],
        patch_height: int | None = ...,
        patch_width: int | None = ...,
    ) -> list[torch.Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> list[torch.Tensor]: ...

class DPTDepthEstimationHead(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: list[torch.Tensor]) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

@auto_docstring(custom_intro=...)
class DPTForDepthEstimation(DPTPreTrainedModel):
    def __init__(self, config) -> None: ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        head_mask: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_hidden_states: bool | None = ...,
        **kwargs,
    ) -> DepthEstimatorOutput: ...

class DPTSemanticSegmentationHead(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: list[torch.Tensor]) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DPTAuxiliaryHead(nn.Module):
    def __init__(self, config: DPTConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

@auto_docstring
class DPTForSemanticSegmentation(DPTPreTrainedModel):
    def __init__(self, config: DPTConfig) -> None: ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        head_mask: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_hidden_states: bool | None = ...,
        **kwargs,
    ) -> SemanticSegmenterOutput: ...

__all__ = [
    "DPTForDepthEstimation",
    "DPTForSemanticSegmentation",
    "DPTModel",
    "DPTPreTrainedModel",
]
