from ...processing_utils import ProcessingKwargs, ProcessorMixin

"""
Processor class for VisionTextDualEncoder
"""

class VisionTextDualEncoderProcessorKwargs(ProcessingKwargs, total=False):
    _defaults = ...

class VisionTextDualEncoderProcessor(ProcessorMixin):
    attributes = ...
    image_processor_class = ...
    tokenizer_class = ...
    def __init__(self, image_processor=..., tokenizer=..., **kwargs) -> None: ...
    @property
    def feature_extractor_class(self):  # -> str:
        ...
    @property
    def feature_extractor(self): ...

__all__ = ["VisionTextDualEncoderProcessor"]
