from collections.abc import Callable
from typing import Any
import functools

logger = ...
cached_property = functools.cached_property

def cached_property_clear(obj, name) -> None: ...

class _LazyClass:
    @cached_property
    def PIL_Image(self) -> Any: ...
    @cached_property
    def numpy(self) -> Any: ...
    @cached_property
    def tabulate(self) -> Callable[..., str]: ...

Lazy = ...
