from torch._C import (
    _add_docstr as _add_docstr,
    _special as _special,
)
from torch._torch_docs import (
    common_args as common_args,
    multi_dim_common as multi_dim_common,
)

import torch

__all__ = [
    "airy_ai",
    "bessel_j0",
    "bessel_j1",
    "bessel_y0",
    "bessel_y1",
    "chebyshev_polynomial_t",
    "chebyshev_polynomial_u",
    "chebyshev_polynomial_v",
    "chebyshev_polynomial_w",
    "digamma",
    "entr",
    "erf",
    "erfc",
    "erfcx",
    "erfinv",
    "exp2",
    "expit",
    "expm1",
    "gammainc",
    "gammaincc",
    "gammaln",
    "hermite_polynomial_h",
    "hermite_polynomial_he",
    "i0",
    "i0e",
    "i1",
    "i1e",
    "laguerre_polynomial_l",
    "legendre_polynomial_p",
    "log1p",
    "log_ndtr",
    "log_softmax",
    "logit",
    "logsumexp",
    "modified_bessel_i0",
    "modified_bessel_i1",
    "modified_bessel_k0",
    "modified_bessel_k1",
    "multigammaln",
    "ndtr",
    "ndtri",
    "polygamma",
    "psi",
    "round",
    "scaled_modified_bessel_k0",
    "scaled_modified_bessel_k1",
    "shifted_chebyshev_polynomial_t",
    "shifted_chebyshev_polynomial_u",
    "shifted_chebyshev_polynomial_v",
    "shifted_chebyshev_polynomial_w",
    "sinc",
    "softmax",
    "spherical_bessel_j0",
    "xlog1py",
    "xlogy",
    "zeta",
]
Tensor = torch.Tensor

def entr(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def psi(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def digamma(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def gammaln(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def polygamma(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def erf(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def erfc(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def erfcx(input: Tensor) -> Tensor: ...
def erfinv(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def logit(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def logsumexp(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def expit(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def exp2(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def expm1(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def xlog1py(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def xlogy(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def i0(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def i0e(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def i1(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def i1e(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def ndtr(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def ndtri(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def log_ndtr(input: Tensor) -> Tensor: ...
def log1p(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def sinc(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def round(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def softmax(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def log_softmax(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def zeta(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def multigammaln(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def gammainc(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def gammaincc(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def airy_ai(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def bessel_j0(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def bessel_j1(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def bessel_y0(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def bessel_y1(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def chebyshev_polynomial_t(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def chebyshev_polynomial_u(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def chebyshev_polynomial_v(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def chebyshev_polynomial_w(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def hermite_polynomial_h(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def hermite_polynomial_he(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def laguerre_polynomial_l(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def legendre_polynomial_p(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def modified_bessel_i0(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def modified_bessel_i1(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def modified_bessel_k0(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def modified_bessel_k1(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
def scaled_modified_bessel_k0(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def scaled_modified_bessel_k1(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def shifted_chebyshev_polynomial_t(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def shifted_chebyshev_polynomial_u(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def shifted_chebyshev_polynomial_v(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def shifted_chebyshev_polynomial_w(
    input: Tensor, *args: object, **kwargs: object
) -> Tensor: ...
def spherical_bessel_j0(input: Tensor, *args: object, **kwargs: object) -> Tensor: ...
