from torchvision.transforms.v2 import functional as F

import torch

from ...image_utils import SizeDict
from ...processing_utils import Unpack, VideosKwargs
from ...video_processing_utils import BaseVideoProcessor
from ...video_utils import VideoMetadata

logger = ...
DEFAULT_SYSTEM_MESSAGE = ...
DEFAULT_VIDEO_INTRO = ...
DEFAULT_MEDIA_OUTTRO = ...
FRAME_TIMESTAMP_MESSAGE = ...
MAX_IMAGE_SIZE = ...

def get_max_height_width(videos: list[torch.Tensor]) -> list[int]: ...
def get_resize_output_image_size(
    video, resolution_max_side: int
) -> tuple[int, int]: ...

class SmolVLMVideoProcessorInitKwargs(VideosKwargs):
    max_image_size: dict[str, int] | None
    do_pad: bool | None

class SmolVLMVideoProcessor(BaseVideoProcessor):
    resample = ...
    size = ...
    max_image_size = ...
    image_mean = ...
    image_std = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    do_pad = ...
    do_sample_frames = ...
    valid_kwargs = SmolVLMVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[SmolVLMVideoProcessorInitKwargs]) -> None: ...
    def resize(
        self,
        video: torch.Tensor,
        size: SizeDict,
        interpolation: F.InterpolationMode | None = ...,
        antialias: bool = ...,
        **kwargs,
    ) -> torch.Tensor: ...
    def pad(
        self,
        video: torch.Tensor,
        padded_size: tuple[int, int],
        max_num_frames: int,
        fill: int = ...,
        return_pixel_mask: bool = ...,
    ):  # -> tuple[Any | Tensor, Tensor | None]:
        ...
    def sample_frames(
        self,
        metadata: VideoMetadata,
        num_frames: int | None = ...,
        fps: float | None = ...,
        skip_secs: int | None = ...,
        **kwargs,
    ):  # -> NDArray[Any]:
        ...

__all__ = ["SmolVLMVideoProcessor"]
