from collections.abc import Callable

from .backend_config import DTypeWithConstraints

__all__: list[str] = ...
_ConvMetadata = ...
_Conv1dMetadata = ...
_Conv2dMetadata = ...
_Conv3dMetadata = ...
_FIXED_QPARAM_OP_0TO1_CONSTRAINTS = ...
_FIXED_QPARAM_OP_NEG1TO1_CONSTRAINTS = ...
_FIXED_QPARAMS_OP_TO_CONSTRAINTS: dict[Callable | str, DTypeWithConstraints] = ...
