from .modeling_depth_pro import DepthProDepthEstimatorOutput
from ...image_processing_utils_fast import BaseImageProcessorFast
from ...utils import TensorType, auto_docstring
from ...utils.import_utils import requires

"""Fast Image processor class for DepthPro."""
logger = ...

@auto_docstring
@requires(backends=("torchvision", "torch"))
class DepthProImageProcessorFast(BaseImageProcessorFast):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    def post_process_depth_estimation(
        self,
        outputs: DepthProDepthEstimatorOutput,
        target_sizes: None | TensorType | list[tuple[int, int]] = ...,
    ) -> list[dict[str, TensorType]]: ...

__all__ = ["DepthProImageProcessorFast"]
