from dataclasses import dataclass

from torch import nn

import torch

from .configuration_videomae import VideoMAEConfig
from ...modeling_layers import GradientCheckpointingLayer
from ...modeling_outputs import BaseModelOutput, ImageClassifierOutput
from ...modeling_utils import PreTrainedModel
from ...processing_utils import Unpack
from ...utils import ModelOutput, TransformersKwargs, auto_docstring
from ...utils.generic import can_return_tuple, check_model_inputs

"""PyTorch VideoMAE (masked autoencoder) model."""
logger = ...

@dataclass
@auto_docstring(custom_intro=...)
class VideoMAEDecoderOutput(ModelOutput):
    logits: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

@dataclass
@auto_docstring(custom_intro=...)
class VideoMAEForPreTrainingOutput(ModelOutput):
    loss: torch.FloatTensor | None = ...
    logits: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor] | None = ...
    attentions: tuple[torch.FloatTensor] | None = ...

def get_sinusoid_encoding_table(n_position, d_hid):  # -> Tensor:
    ...

class VideoMAEEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values, bool_masked_pos):  # -> Any:
        ...

class VideoMAEPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values):  # -> Any:
        ...

def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = ...,
    **kwargs,
):  # -> tuple[Tensor, Tensor]:
    ...

class VideoMAESelfAttention(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(
        self, hidden_states, head_mask: torch.Tensor | None = ...
    ) -> tuple[torch.Tensor, torch.Tensor]: ...

class VideoMAESelfOutput(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...

class VideoMAEAttention(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def prune_heads(self, heads: set[int]):  # -> None:
        ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...

class VideoMAEIntermediate(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...

class VideoMAEOutput(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...

class VideoMAELayer(GradientCheckpointingLayer):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> torch.Tensor: ...

class VideoMAEEncoder(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, head_mask: torch.Tensor | None = ...
    ) -> BaseModelOutput: ...

@auto_docstring
class VideoMAEPreTrainedModel(PreTrainedModel):
    config: VideoMAEConfig
    base_model_prefix = ...
    main_input_name = ...
    supports_gradient_checkpointing = ...
    _no_split_modules = ...
    _supports_sdpa = ...
    _supports_flash_attn = ...
    _supports_flex_attn = ...
    _supports_attention_backend = ...
    _can_record_outputs = ...

@auto_docstring
class VideoMAEModel(VideoMAEPreTrainedModel):
    def __init__(self, config) -> None: ...
    def get_input_embeddings(self):  # -> VideoMAEPatchEmbeddings:
        ...
    @check_model_inputs
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        bool_masked_pos: torch.BoolTensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> BaseModelOutput: ...

class VideoMAEDecoder(nn.Module):
    def __init__(self, config: VideoMAEConfig) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, return_token_num: int
    ):  # -> VideoMAEDecoderOutput:
        ...

@auto_docstring(custom_intro=...)
class VideoMAEForPreTraining(VideoMAEPreTrainedModel):
    def __init__(self, config) -> None: ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        bool_masked_pos: torch.BoolTensor,
        head_mask: torch.Tensor | None = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> VideoMAEForPreTrainingOutput: ...

@auto_docstring(custom_intro=...)
class VideoMAEForVideoClassification(VideoMAEPreTrainedModel):
    def __init__(self, config) -> None: ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.Tensor | None = ...,
        head_mask: torch.Tensor | None = ...,
        labels: torch.Tensor | None = ...,
        **kwargs: Unpack[TransformersKwargs],
    ) -> ImageClassifierOutput: ...

__all__ = [
    "VideoMAEForPreTraining",
    "VideoMAEForVideoClassification",
    "VideoMAEModel",
    "VideoMAEPreTrainedModel",
]
