from ...processing_utils import Unpack, VideosKwargs
from ...video_processing_utils import BaseVideoProcessor

"""Fast Video processor class for VJEPA2."""

class VJEPA2VideoProcessorInitKwargs(VideosKwargs): ...

class VJEPA2VideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    crop_size = ...
    do_resize = ...
    do_rescale = ...
    do_center_crop = ...
    do_normalize = ...
    valid_kwargs = VJEPA2VideoProcessorInitKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[VJEPA2VideoProcessorInitKwargs]) -> None: ...

__all__ = ["VJEPA2VideoProcessor"]
