from typing import Any
from torch import nn

import torch

from .configuration_dinov3_convnext import DINOv3ConvNextConfig
from ...modeling_outputs import BaseModelOutputWithPoolingAndNoAttention
from ...modeling_utils import PreTrainedModel
from ...utils import auto_docstring
from ...utils.generic import can_return_tuple

"""PyTorch ConvNext model."""
logger = ...

def drop_path(
    input: torch.Tensor, drop_prob: float = ..., training: bool = ...
) -> torch.Tensor: ...

class DINOv3ConvNextDropPath(nn.Module):
    def __init__(self, drop_prob: float | None = ...) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class DINOv3ConvNextLayerNorm(nn.LayerNorm):
    def __init__(self, *args, data_format=..., **kwargs) -> None: ...
    def forward(self, features: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DINOv3ConvNextLayer(nn.Module):
    def __init__(
        self, config: DINOv3ConvNextConfig, channels: int, drop_path: float = ...
    ) -> None: ...
    def forward(self, features: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DINOv3ConvNextStage(nn.Module):
    def __init__(self, config: DINOv3ConvNextConfig, stage_idx: int) -> None: ...
    def forward(self, features: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

@auto_docstring
class DINOv3ConvNextPreTrainedModel(PreTrainedModel):
    config: DINOv3ConvNextConfig
    base_model_prefix = ...
    main_input_name = ...
    _no_split_modules = ...

@auto_docstring
class DINOv3ConvNextModel(DINOv3ConvNextPreTrainedModel):
    def __init__(self, config: DINOv3ConvNextConfig) -> None: ...
    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor,
        output_hidden_states: bool | None = ...,
    ) -> BaseModelOutputWithPoolingAndNoAttention: ...

__all__ = ["DINOv3ConvNextModel", "DINOv3ConvNextPreTrainedModel"]
