from ...processing_utils import Unpack, VideosKwargs
from ...video_processing_utils import BaseVideoProcessor
from ...video_utils import VideoMetadata

"""Fast Video processor class for InternVL."""

class InternVLVideoProcessorInitKwargs(VideosKwargs):
    initial_shift: bool | float | int

class InternVLVideoProcessor(BaseVideoProcessor):
    resample = ...
    image_mean = ...
    image_std = ...
    size = ...
    do_resize = ...
    do_rescale = ...
    do_normalize = ...
    do_convert_rgb = ...
    initial_shift = ...
    do_sample_frames = ...
    valid_kwargs = InternVLVideoProcessorInitKwargs
    model_input_names = ...
    def __init__(self, **kwargs: Unpack[InternVLVideoProcessorInitKwargs]) -> None: ...
    def sample_frames(
        self,
        metadata: VideoMetadata,
        num_frames: int | None = ...,
        fps: float | None = ...,
        initial_shift: bool | float | None = ...,
        **kwargs,
    ):  # -> Tensor:
        ...

__all__ = ["InternVLVideoProcessor"]
