from collections import defaultdict

import dataclasses

from torch.onnx._internal.exporter import _registration

import torch
import torch._export.serde.schema
import torch.fx

"""Compatibility analyzer for PyTorch models."""

@dataclasses.dataclass
class ModelInfo:
    parameter_count: defaultdict[torch.dtype, int] = ...
    buffer_count: defaultdict[torch.dtype, int] = ...
    fx_node_count: int = ...
    fx_node_op_count: defaultdict[str, int] = ...
    fx_node_target_count: defaultdict[str, int] = ...
    dispatch_failures: list[tuple[torch.fx.Node, str]] = ...
    inputs: dict[str, torch._export.serde.schema.TensorMeta] = ...
    outputs: dict[str, torch._export.serde.schema.TensorMeta] = ...

def analyze(
    exported_program: torch.export.ExportedProgram,
    registry: _registration.ONNXRegistry | None = ...,
    file=...,
) -> None: ...
def compare_ops(
    program_a: torch.export.ExportedProgram, program_b: torch.export.ExportedProgram
) -> tuple[set[str], set[str]]: ...
