import torch.onnx.errors

"""Error classes for the ONNX exporter."""

class TorchExportError(torch.onnx.errors.OnnxExporterError): ...
class ConversionError(torch.onnx.errors.OnnxExporterError): ...
class DispatchError(ConversionError): ...
class GraphConstructionError(ConversionError): ...
