from collections.abc import Sequence

from torch.onnx._internal._lazy_import import onnxscript_ir as ir

_ONNX_DOMAIN = ...
logger = ...

def rename_inputs(model: ir.Model, new_names: Sequence[str]) -> None: ...
def rename_outputs(model: ir.Model, new_names: Sequence[str]) -> None: ...
def rename_axis(model: ir.Model, rename_mapping: dict[str, str]) -> None: ...
def add_torchlib_common_imports(model: ir.Model, opset_version: int = ...) -> None: ...
def add_opset_imports(model: ir.Model) -> None: ...
