from collections.abc import Callable, Sequence

import os

from torch.onnx._internal._lazy_import import (
    onnx,
    onnxscript_ir as ir,
)

import onnxruntime as ort
import torch

__all__ = ["ONNXProgram"]
_LARGE_MODEL_THRESHOLD = ...
_NP_UNSUPPORTED_DTYPES_8BIT = ...
logger = ...

class ONNXProgram:
    def __init__(
        self, model: ir.Model, exported_program: torch.export.ExportedProgram | None
    ) -> None: ...
    def __call__(self, *args, **kwargs) -> Sequence[torch.Tensor]: ...
    def call_reference(self, *args, **kwargs) -> Sequence[torch.Tensor]: ...
    def compute_values(
        self, value_names: Sequence[str], args=..., kwargs=...
    ) -> Sequence[torch.Tensor]: ...
    @property
    def model_proto(self) -> onnx.ModelProto: ...
    def optimize(self) -> None: ...
    def save(
        self,
        destination: str | os.PathLike,
        *,
        include_initializers: bool = ...,
        keep_initializers_as_inputs: bool = ...,
        external_data: bool | None = ...,
    ) -> None: ...
    def apply_weights(self, state_dict: dict[str, torch.Tensor]) -> None: ...
    def initialize_inference_session(
        self, initializer: Callable[[str | bytes], ort.InferenceSession] = ...
    ) -> None: ...
    def release(self) -> None: ...
