from collections.abc import Callable

import dataclasses
import types

from torch.onnx._internal.exporter import _schemas

import torch
import torch._ops

"""Module for handling ATen to ONNX functions registration.

https://github.com/pytorch/pytorch/blob/6aa5bb1a76dee8112f1a9e7c194c790b5cdc6462/torch/onnx/_internal/fx/registration.py
"""
type TorchOp = torch._ops.OpOverload | types.BuiltinFunctionType | Callable
logger = ...

@dataclasses.dataclass
class OnnxDecompMeta:
    onnx_function: Callable
    fx_target: TorchOp
    signature: _schemas.OpSignature | None
    is_custom: bool = ...
    is_complex: bool = ...
    opset_introduced: int = ...
    device: str | None = ...
    skip_signature_inference: bool = ...
    def __post_init__(self) -> None: ...

class ONNXRegistry:
    def __init__(self) -> None: ...
    @property
    def opset_version(self) -> int: ...
    @classmethod
    def from_torchlib(cls, opset_version=...) -> ONNXRegistry: ...
    def register_op(
        self, target: TorchOp, function: Callable, is_complex: bool = ...
    ) -> None: ...
    def get_decomps(self, target: TorchOp) -> list[OnnxDecompMeta]: ...
    def is_registered(self, target: TorchOp) -> bool: ...
