from onnxscript import ir

import onnxscript

"""Subclass of ir.Value that supports Python operators."""

class SymbolicTensor(ir.Value):
    def __init__(
        self,
        opset: onnxscript.values.Opset,
        name: str | None = ...,
        shape: ir.Shape | None = ...,
        type: ir.TypeProtocol | None = ...,
        doc_string: str | None = ...,
        const_value: ir.TensorProtocol | None = ...,
    ) -> None: ...
    @property
    def rank(self) -> int | None: ...
    def __mod__(self, other): ...
    def __ne__(self, other) -> bool: ...
    def __neg__(self): ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __rand__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __matmul__(self, other): ...
    def __pow__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __truediv__(self, other): ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
