from collections.abc import Sequence
from torch import Tensor as Tensor
from torch import return_types
from torch._C import (
    _add_docstr as _add_docstr,
    _linalg as _linalg,
)

class LinAlgError(RuntimeError): ...

# These are bound via `_add_docstr(_linalg.linalg_*, ...)` upstream, so the
# generator emitted them as bare `= ...` and every call site inferred Unknown.
def eigh(
    A: Tensor, UPLO: str = ..., *, out: object = ...
) -> return_types._linalg_eigh: ...
def svd(
    A: Tensor, full_matrices: bool = ..., *, driver: str | None = ..., out: object = ...
) -> return_types._linalg_svd: ...
def svdvals(A: Tensor, *, driver: str | None = ..., out: object = ...) -> Tensor: ...
def solve(A: Tensor, B: Tensor, *, left: bool = ..., out: object = ...) -> Tensor: ...
def norm(
    A: Tensor,
    ord: float | str | None = ...,
    dim: int | Sequence[int] | None = ...,
    keepdim: bool = ...,
    *,
    out: object = ...,
    dtype: object = ...,
) -> Tensor: ...
def vector_norm(
    x: Tensor,
    ord: float = ...,
    dim: int | Sequence[int] | None = ...,
    keepdim: bool = ...,
    *,
    out: object = ...,
    dtype: object = ...,
) -> Tensor: ...

common_notes = ...
cross = ...
cholesky = ...
cholesky_ex = ...
inv = ...
solve_ex = ...
inv_ex = ...
det = ...
slogdet = ...
eig = ...
eigvals = ...
eigvalsh = ...
householder_product = ...
ldl_factor = ...
ldl_factor_ex = ...
ldl_solve = ...
lstsq = ...
matrix_power = ...
matrix_rank = ...
matrix_norm = ...
matmul = ...
diagonal = ...
multi_dot = ...
cond = ...
pinv = ...
matrix_exp = ...
solve_triangular = ...
lu_factor = ...
lu_factor_ex = ...
lu_solve = ...
lu = ...
tensorinv = ...
tensorsolve = ...
qr = ...
vander = ...
vecdot = ...
