from torch import Tensor as Tensor
from torch._C import (
    _add_docstr as _add_docstr,
    _linalg as _linalg,
)

class LinAlgError(RuntimeError): ...

common_notes = ...
cross = ...
cholesky = ...
cholesky_ex = ...
inv = ...
solve_ex = ...
inv_ex = ...
det = ...
slogdet = ...
eig = ...
eigvals = ...
eigh = ...
eigvalsh = ...
householder_product = ...
ldl_factor = ...
ldl_factor_ex = ...
ldl_solve = ...
lstsq = ...
matrix_power = ...
matrix_rank = ...
norm = ...
vector_norm = ...
matrix_norm = ...
matmul = ...
diagonal = ...
multi_dot = ...
svd = ...
svdvals = ...
cond = ...
pinv = ...
matrix_exp = ...
solve = ...
solve_triangular = ...
lu_factor = ...
lu_factor_ex = ...
lu_solve = ...
lu = ...
tensorinv = ...
tensorsolve = ...
qr = ...
vander = ...
vecdot = ...
