from collections.abc import Sequence
from typing import Any

from slack_sdk.models.basic_objects import JsonObject, JsonValidator
from slack_sdk.models.messages import Link

ButtonStyles = ...
DynamicSelectElementTypes = ...

class TextObject(JsonObject):
    logger = ...
    @property
    def subtype(self) -> str | None: ...
    @classmethod
    def parse(
        cls, text: str | dict[str, Any] | TextObject, default_type: str = ...
    ) -> TextObject | None: ...
    def __init__(
        self,
        text: str,
        type: str | None = ...,
        subtype: str | None = ...,
        emoji: bool | None = ...,
        **kwargs,
    ) -> None: ...

class PlainTextObject(TextObject):
    type = ...
    @property
    def attributes(self) -> set[str]: ...
    def __init__(self, *, text: str, emoji: bool | None = ...) -> None: ...
    @staticmethod
    def from_str(text: str) -> PlainTextObject: ...
    @staticmethod
    def direct_from_string(text: str) -> dict[str, Any]: ...

class MarkdownTextObject(TextObject):
    type = ...
    @property
    def attributes(self) -> set[str]: ...
    def __init__(self, *, text: str, verbatim: bool | None = ...) -> None: ...
    @staticmethod
    def from_str(text: str) -> MarkdownTextObject: ...
    @staticmethod
    def direct_from_string(text: str) -> dict[str, Any]: ...
    @staticmethod
    def from_link(link: Link, title: str = ...) -> MarkdownTextObject: ...
    @staticmethod
    def direct_from_link(link: Link, title: str = ...) -> dict[str, Any]: ...

class RawTextObject(TextObject):
    type = ...
    @property
    def attributes(self) -> set[str]: ...
    def __init__(self, *, text: str) -> None: ...
    @staticmethod
    def from_str(text: str) -> RawTextObject: ...
    @staticmethod
    def direct_from_string(text: str) -> dict[str, Any]: ...

class Option(JsonObject):
    attributes: set[str] = ...
    logger = ...
    label_max_length = ...
    value_max_length = ...
    def __init__(
        self,
        *,
        value: str,
        label: str | None = ...,
        text: str | dict[str, Any] | TextObject | None = ...,
        description: str | dict[str, Any] | TextObject | None = ...,
        url: str | None = ...,
        **others: dict[str, Any],
    ) -> None: ...
    @classmethod
    def parse_all(
        cls, options: Sequence[dict[str, Any] | Option] | None
    ) -> list[Option] | None: ...
    def to_dict(self, option_type: str = ...) -> dict[str, Any]: ...
    @staticmethod
    def from_single_value(value_and_label: str) -> Option: ...

class OptionGroup(JsonObject):
    attributes: set[str] = ...
    label_max_length = ...
    options_max_length = ...
    logger = ...
    def __init__(
        self,
        *,
        label: str | dict[str, Any] | TextObject | None = ...,
        options: Sequence[dict[str, Any] | Option],
        **others: dict[str, Any],
    ) -> None: ...
    @classmethod
    def parse_all(
        cls, option_groups: Sequence[dict[str, Any] | OptionGroup] | None
    ) -> list[OptionGroup] | None: ...
    def to_dict(self, option_type: str = ...) -> dict[str, Any]: ...

class ConfirmObject(JsonObject):
    attributes: set[str] = ...
    title_max_length = ...
    text_max_length = ...
    confirm_max_length = ...
    deny_max_length = ...
    @classmethod
    def parse(cls, confirm: ConfirmObject | dict[str, Any]) -> ConfirmObject | None: ...
    def __init__(
        self,
        *,
        title: str | dict[str, Any] | PlainTextObject,
        text: str | dict[str, Any] | TextObject,
        confirm: str | dict[str, Any] | PlainTextObject = ...,
        deny: str | dict[str, Any] | PlainTextObject = ...,
        style: str | None = ...,
    ) -> None: ...
    @JsonValidator(...)
    def title_length(self) -> bool: ...
    @JsonValidator(...)
    def text_length(self) -> bool: ...
    @JsonValidator(...)
    def confirm_length(self) -> bool: ...
    @JsonValidator(...)
    def deny_length(self) -> bool: ...
    def to_dict(self, option_type: str = ...) -> dict[str, Any]: ...

class DispatchActionConfig(JsonObject):
    @classmethod
    def parse(
        cls, config: DispatchActionConfig | dict[str, Any]
    ) -> DispatchActionConfig | None: ...
    def __init__(self, *, trigger_actions_on: list[Any] | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class FeedbackButtonObject(JsonObject):
    attributes: set[str] = ...
    text_max_length = ...
    value_max_length = ...
    @classmethod
    def parse(
        cls, feedback_button: FeedbackButtonObject | dict[str, Any]
    ) -> FeedbackButtonObject | None: ...
    def __init__(
        self,
        *,
        text: str | dict[str, Any] | PlainTextObject,
        accessibility_label: str | None = ...,
        value: str,
        **others: dict[str, Any],
    ) -> None: ...
    @JsonValidator(...)
    def text_length(self) -> bool: ...
    @JsonValidator(...)
    def value_length(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...

class WorkflowTrigger(JsonObject):
    def __init__(
        self,
        *,
        url: str,
        customizable_input_parameters: list[dict[str, str]] | None = ...,
    ) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class Workflow(JsonObject):
    def __init__(self, *, trigger: WorkflowTrigger | dict) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class SlackFile(JsonObject):
    def __init__(self, *, id: str | None = ..., url: str | None = ...) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
