from torch.utils._pytree import (
    tree_flatten as tree_flatten,
    tree_unflatten as tree_unflatten,
)

from .closure import (
    add_step_closure as add_step_closure,
    run_step_closures as run_step_closures,
)

def mark_step(device: str = ..., wait=...) -> None: ...
def wait_device_ops(devices=...) -> None: ...
def sync_multi(tensors, devices) -> None: ...
def get_tensor_id(tensor) -> int: ...
def to_cpu(tensors, devices=...) -> PyTree: ...
def save(tensors, *args, **kwargs) -> None: ...
