class ClosureHandler:
    def __init__(self) -> None: ...
    def run(self, closure) -> None: ...
    def __call__(self, closures) -> None: ...

class AsyncClosureHandler(ClosureHandler):
    def __init__(self, max_queue_size=...) -> None: ...
    def start_event_loop(self) -> None: ...
    def run(self, closure) -> None: ...

def add_step_closure(closure, args=..., run_async=...) -> None: ...
def run_step_closures() -> DeviceContext: ...
