from typing import Any

class DeviceContext:
    _CONTEXTS: dict[str, Any] = ...
    _CONTEXTS_LOCK = ...
    def __init__(self, device: str) -> None: ...

def get_device_context(device: str | None = ...) -> DeviceContext: ...
