class Clock:
    def now(self) -> float: ...

class SignatureVerifier:
    def __init__(self, signing_secret: str, clock: Clock = ...) -> None: ...
    def is_valid_request(self, body: str | bytes, headers: dict[str, str]) -> bool: ...
    def is_valid(self, body: str | bytes, timestamp: str, signature: str) -> bool: ...
    def generate_signature(
        self, *, timestamp: str, body: str | bytes
    ) -> str | None: ...
