from typing import Any
from dataclasses import dataclass

from torch import nn

import torch

from .configuration_dinat import DinatConfig
from ...modeling_outputs import BackboneOutput
from ...modeling_utils import PreTrainedModel
from ...utils import ModelOutput, auto_docstring, is_natten_available
from ...utils.backbone_utils import BackboneMixin

"""PyTorch Dilated Neighborhood Attention Transformer model."""
if is_natten_available(): ...
else:
    def natten2dqkrpb(*args, **kwargs): ...
    def natten2dav(*args, **kwargs): ...

logger = ...

@dataclass
@auto_docstring(custom_intro=...)
class DinatEncoderOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor, ...] | None = ...
    attentions: tuple[torch.FloatTensor, ...] | None = ...
    reshaped_hidden_states: tuple[torch.FloatTensor, ...] | None = ...

@dataclass
@auto_docstring(custom_intro=...)
class DinatModelOutput(ModelOutput):
    last_hidden_state: torch.FloatTensor | None = ...
    pooler_output: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor, ...] | None = ...
    attentions: tuple[torch.FloatTensor, ...] | None = ...
    reshaped_hidden_states: tuple[torch.FloatTensor, ...] | None = ...

@dataclass
@auto_docstring(
    custom_intro="""
    Dinat outputs for image classification.
    """
)
class DinatImageClassifierOutput(ModelOutput):
    loss: torch.FloatTensor | None = ...
    logits: torch.FloatTensor | None = ...
    hidden_states: tuple[torch.FloatTensor, ...] | None = ...
    attentions: tuple[torch.FloatTensor, ...] | None = ...
    reshaped_hidden_states: tuple[torch.FloatTensor, ...] | None = ...

class DinatEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self, pixel_values: torch.FloatTensor | None
    ) -> tuple[torch.Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[torch.Tensor]: ...

class DinatPatchEmbeddings(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(self, pixel_values: torch.FloatTensor | None) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DinatDownsampler(nn.Module):
    def __init__(self, dim: int, norm_layer: nn.Module = ...) -> None: ...
    def forward(self, input_feature: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

def drop_path(
    input: torch.Tensor, drop_prob: float = ..., training: bool = ...
) -> torch.Tensor: ...

class DinatDropPath(nn.Module):
    def __init__(self, drop_prob: float | None = ...) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...
    def extra_repr(self) -> str: ...

class NeighborhoodAttention(nn.Module):
    def __init__(self, config, dim, num_heads, kernel_size, dilation) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, output_attentions: bool | None = ...
    ) -> tuple[torch.Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[torch.Tensor]: ...

class NeighborhoodAttentionOutput(nn.Module):
    def __init__(self, config, dim) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, input_tensor: torch.Tensor
    ) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class NeighborhoodAttentionModule(nn.Module):
    def __init__(self, config, dim, num_heads, kernel_size, dilation) -> None: ...
    def prune_heads(self, heads):  # -> None:
        ...
    def forward(
        self, hidden_states: torch.Tensor, output_attentions: bool | None = ...
    ) -> tuple[torch.Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[torch.Tensor]: ...

class DinatIntermediate(nn.Module):
    def __init__(self, config, dim) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DinatOutput(nn.Module):
    def __init__(self, config, dim) -> None: ...
    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor: ...
    def __call__(self, *args: Any, **kwargs: Any) -> torch.Tensor: ...

class DinatLayer(nn.Module):
    def __init__(
        self, config, dim, num_heads, dilation, drop_path_rate=...
    ) -> None: ...
    def maybe_pad(
        self, hidden_states, height, width
    ):  # -> tuple[Tensor | Any, tuple[Literal[0], Literal[0], Literal[0], int, Literal[0], int] | tuple[Literal[0], Literal[0], Literal[0], Literal[0], Literal[0], Literal[0]]]:
        ...
    def forward(
        self, hidden_states: torch.Tensor, output_attentions: bool | None = ...
    ) -> tuple[torch.Tensor, torch.Tensor]: ...
    def __call__(
        self, *args: Any, **kwargs: Any
    ) -> tuple[torch.Tensor, torch.Tensor]: ...

class DinatStage(nn.Module):
    def __init__(
        self, config, dim, depth, num_heads, dilations, drop_path_rate, downsample
    ) -> None: ...
    def forward(
        self, hidden_states: torch.Tensor, output_attentions: bool | None = ...
    ) -> tuple[torch.Tensor]: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple[torch.Tensor]: ...

class DinatEncoder(nn.Module):
    def __init__(self, config) -> None: ...
    def forward(
        self,
        hidden_states: torch.Tensor,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        output_hidden_states_before_downsampling: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | DinatEncoderOutput: ...
    def __call__(self, *args: Any, **kwargs: Any) -> tuple | DinatEncoderOutput: ...

@auto_docstring
class DinatPreTrainedModel(PreTrainedModel):
    config: DinatConfig
    base_model_prefix = ...
    main_input_name = ...

@auto_docstring
class DinatModel(DinatPreTrainedModel):
    def __init__(self, config, add_pooling_layer=...) -> None: ...
    def get_input_embeddings(self):  # -> DinatPatchEmbeddings:
        ...
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | DinatModelOutput: ...

@auto_docstring(custom_intro=...)
class DinatForImageClassification(DinatPreTrainedModel):
    def __init__(self, config) -> None: ...
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.FloatTensor | None = ...,
        labels: torch.LongTensor | None = ...,
        output_attentions: bool | None = ...,
        output_hidden_states: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> tuple | DinatImageClassifierOutput: ...

@auto_docstring(custom_intro=...)
class DinatBackbone(DinatPreTrainedModel, BackboneMixin):
    def __init__(self, config) -> None: ...
    def get_input_embeddings(self):  # -> DinatPatchEmbeddings:
        ...
    @auto_docstring
    def forward(
        self,
        pixel_values: torch.Tensor,
        output_hidden_states: bool | None = ...,
        output_attentions: bool | None = ...,
        return_dict: bool | None = ...,
    ) -> BackboneOutput: ...

__all__ = [
    "DinatBackbone",
    "DinatForImageClassification",
    "DinatModel",
    "DinatPreTrainedModel",
]
