class DiGraph:
    def __init__(self) -> None: ...
    def add_node(self, n, **kwargs) -> None: ...
    def add_edge(self, u, v) -> None: ...
    def successors(self, n): ...
    def predecessors(self, n): ...
    @property
    def edges(self) -> Generator[tuple[Any, Any], Any, None]: ...
    @property
    def nodes(self) -> dict[Any, Any]: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __contains__(self, n) -> bool: ...
    def forward_transitive_closure(self, src: str) -> set[str]: ...
    def backward_transitive_closure(self, src: str) -> set[str]: ...
    def all_paths(self, src: str, dst: str) -> DiGraph | str: ...
    def first_path(self, dst: str) -> list[str]: ...
    def to_dot(self) -> str: ...
