from typing import Any, Literal

__serialization_id_record_name__ = ...

class _HasStorage:
    def __init__(self, storage) -> None: ...
    def storage(self) -> Any: ...

class DirectoryReader:
    def __init__(self, directory) -> None: ...
    def get_record(self, name) -> bytes: ...
    def get_storage_from_record(self, name, numel, dtype) -> _HasStorage: ...
    def has_record(self, path) -> bool: ...
    def get_all_records(self) -> list[str]: ...
    def serialization_id(self) -> bytes | Literal[""]: ...
