from dataclasses import dataclass
from typing import Any

from .rocm_kernel import ROCmTemplateCaller
from ..common import KernelTemplate
from ...ir import Buffer, Layout
from ...utils import IndentedBuffer

log = ...

@dataclass(frozen=True)
class ArgInfo:
    name: str
    ty: str

class ROCmTemplate(KernelTemplate):
    index_counter = ...
    gfx9_threads_per_warp = ...
    def __init__(
        self,
        name: str,
        input_nodes: list[Buffer],
        layout: Layout,
        input_reorder: list[int] | None = ...,
    ) -> None: ...
    def generate(self, **kwargs) -> ROCmTemplateCaller: ...
    def header(self) -> IndentedBuffer: ...
    def globals(self) -> IndentedBuffer: ...
    def render(self, **kwargs) -> str: ...
    def get_runtime_arg_info(self) -> list[ArgInfo]: ...
    def get_runtime_arg_values(self, **kwargs) -> list[Any]: ...
