from transformers.models.detr.image_processing_detr_fast import DetrImageProcessorFast

from ...utils import TensorType

logger = ...

class DeformableDetrImageProcessorFast(DetrImageProcessorFast):
    def post_process(self, outputs, target_sizes):  # -> list[dict[str, Tensor | Any]]:
        ...
    def post_process_object_detection(
        self,
        outputs,
        threshold: float = ...,
        target_sizes: TensorType | list[tuple] = ...,
        top_k: int = ...,
    ):  # -> list[Any]:
        ...
    def post_process_segmentation(self): ...
    def post_process_instance(self): ...
    def post_process_panoptic(self): ...
    def post_process_instance_segmentation(self): ...
    def post_process_semantic_segmentation(self): ...
    def post_process_panoptic_segmentation(self): ...

__all__ = ["DeformableDetrImageProcessorFast"]
