from ...processing_utils import ProcessorMixin

"""
Processor class for CLVP
"""
logger = ...

class ClvpProcessor(ProcessorMixin):
    feature_extractor_class = ...
    tokenizer_class = ...
    def __init__(self, feature_extractor, tokenizer) -> None: ...
    def __call__(self, *args, **kwargs):  # -> BatchFeature:
        ...

__all__ = ["ClvpProcessor"]
