from functools import lru_cache

from .doc import add_end_docstrings as add_end_docstrings
from .generic import (
    ExplicitEnum as ExplicitEnum,
    PaddingStrategy as PaddingStrategy,
    TensorType as TensorType,
)
from .hub import PushToHubMixin as PushToHubMixin
from .import_utils import is_tokenizers_available as is_tokenizers_available

WEIGHTS_NAME = ...
WEIGHTS_INDEX_NAME = ...
TF2_WEIGHTS_NAME = ...
TF2_WEIGHTS_INDEX_NAME = ...
TF_WEIGHTS_NAME = ...
FLAX_WEIGHTS_NAME = ...
FLAX_WEIGHTS_INDEX_NAME = ...
SAFE_WEIGHTS_NAME = ...
SAFE_WEIGHTS_INDEX_NAME = ...
CONFIG_NAME = ...
FEATURE_EXTRACTOR_NAME = ...
IMAGE_PROCESSOR_NAME = ...
VIDEO_PROCESSOR_NAME = ...
AUDIO_TOKENIZER_NAME = ...
PROCESSOR_NAME = ...
GENERATION_CONFIG_NAME = ...
MODEL_CARD_NAME = ...
SENTENCEPIECE_UNDERLINE = ...
SPIECE_UNDERLINE = ...
MULTIPLE_CHOICE_DUMMY_INPUTS = ...
DUMMY_INPUTS = ...
DUMMY_MASK = ...

def check_min_version(min_version):  # -> None:
    ...
@lru_cache
def get_available_devices() -> frozenset[str]: ...
