from torch import Tensor
from typing import Self
from collections import namedtuple
from typing import Any

from torch import nn
from torch.fx import GraphModule
from torch.fx.graph import Node

import torch

CUSTOM_MODULE_SUPP_LIST: list[Any] = ...

def reshape_scale(
    scale: torch.Tensor, axis: int, input: torch.Tensor
) -> torch.Tensor: ...

qsheme_mapping_per_tensor_to_per_channel = ...

class _InputEqualizationObserver(nn.Module):
    def __init__(
        self, dtype=..., qscheme=..., quant_min=..., quant_max=..., factory_kwargs=...
    ) -> None: ...
    def forward(self, x_orig) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_input_minmax(self) -> tuple[Tensor, Tensor]: ...
    def set_equalization_scale(self, equalization_scale) -> None: ...
    def calculate_scaled_minmax(self) -> tuple[None, None] | tuple[Tensor, Tensor]: ...

    with_args = ...

class _WeightEqualizationObserver(nn.Module):
    def __init__(
        self, dtype=..., qscheme=..., quant_min=..., quant_max=..., factory_kwargs=...
    ) -> None: ...
    def forward(self, w_orig) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_weight_col_minmax(self) -> tuple[Tensor, Tensor]: ...
    def set_equalization_scale(self, equalization_scale) -> None: ...

    with_args = ...

def calculate_equalization_scale(
    input_obs: _InputEqualizationObserver, weight_obs: _WeightEqualizationObserver
) -> torch.Tensor: ...

class EqualizationQConfig(
    namedtuple("EqualizationQConfig", ["input_activation", "weight"])
):
    __slots__ = ...
    def __new__(cls, input_activation=..., weight=...) -> Self: ...

input_equalization_observer = ...
weight_equalization_observer = ...
default_equalization_qconfig = ...

def fused_module_supports_equalization(module) -> bool: ...
def nn_module_supports_equalization(module) -> bool: ...
def custom_module_supports_equalization(module) -> bool: ...
def node_supports_equalization(node: Node, modules) -> bool: ...
def is_equalization_observer(observer: nn.Module) -> bool: ...
def get_op_node_and_weight_eq_obs(
    input_eq_obs_node: Node, model: GraphModule, modules: dict[str, nn.Module]
) -> tuple[Node | None, _WeightEqualizationObserver | None]: ...
def maybe_get_weight_eq_obs_node(
    op_node: Node, modules: dict[str, nn.Module]
) -> Node | None: ...
def maybe_get_next_input_eq_obs(
    node: Node, modules: dict[str, nn.Module]
) -> _InputEqualizationObserver | None: ...
def maybe_get_next_equalization_scale(
    node: Node, modules: dict[str, nn.Module]
) -> torch.Tensor | None: ...
def scale_input_observer(node: Node, modules: dict[str, nn.Module]) -> None: ...
def scale_weight_node(
    node: Node,
    modules: dict[str, nn.Module],
    equalization_scale: torch.Tensor,
    next_equalization_scale: torch.Tensor | None,
) -> None: ...
def scale_weight_functional(
    op_node: Node,
    model: GraphModule,
    modules: dict[str, nn.Module],
    equalization_scale: torch.Tensor,
    next_equalization_scale: torch.Tensor | None,
) -> None: ...
def clear_weight_quant_obs_node(
    op_node: Node, modules: dict[str, nn.Module]
) -> None: ...
def remove_node(model: GraphModule, node: Node, prev_node: Node) -> None: ...
def update_obs_for_equalization(
    model: GraphModule, modules: dict[str, nn.Module]
) -> dict[str, _WeightEqualizationObserver]: ...
def convert_eq_obs(
    model: GraphModule,
    modules: dict[str, nn.Module],
    weight_eq_obs_dict: dict[str, _WeightEqualizationObserver],
) -> None: ...
def get_layer_sqnr_dict(
    model_a: nn.Module, model_b: nn.Module, x: torch.Tensor
) -> dict[str, float]: ...
def get_equalization_qconfig_dict(
    layer_sqnr_dict: dict[str, float], num_layers_to_equalize: int
) -> Any: ...
