from typing import Any, Self

import torch
import torch.ao.nn.intrinsic
import torch.ao.nn.quantized as nnq

__all__ = ["BNReLU2d", "BNReLU3d"]

class BNReLU2d(nnq.BatchNorm2d):
    _FLOAT_MODULE = torch.ao.nn.intrinsic.BNReLU2d
    def __init__(
        self, num_features, eps=..., momentum=..., device=..., dtype=...
    ) -> None: ...
    def forward(self, input) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...): ...
    @classmethod
    def from_reference(cls, bn_relu, output_scale, output_zero_point) -> Self: ...

class BNReLU3d(nnq.BatchNorm3d):
    _FLOAT_MODULE = torch.ao.nn.intrinsic.BNReLU3d
    def __init__(
        self, num_features, eps=..., momentum=..., device=..., dtype=...
    ) -> None: ...
    def forward(self, input) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    @classmethod
    def from_float(cls, mod, use_precomputed_fake_quant=...): ...
    @classmethod
    def from_reference(cls, bn_relu, output_scale, output_zero_point) -> Self: ...
